"""Bytes the reader-units tests compare with, copied by command (never typed) on 2026-10-05 UTC from:
  the reader README directory of the installation candidate, opsart branch ops/r2d2-v2-epoch03-artifacts-20261002 at
  4a6f7675b8e418e0e7ee55a446250815f3bd5562 (c3po/deployment/reader/c3po-reader.service, c3po-reader.timer,
  c3po-reader-alert.service), and the producer template and values of the e3-20261004-a request
  (W/once-e3-20261004-a/bound/REQUEST.BOUND.json, plan.units[0]: template_b64, placeholders), whose render is the
  installed producer unit (rendered_sha256 662c57b9...bc06, 1674 bytes, KNOWN_COMPLETE; read back by l6-20261004-a).
The SHA-256 of each is written beside it and checked by the tests. Test data only."""
README_SERVICE_SHA256='8d2ff7a91b94e39b8c7a0e91fae34b16dbc9d55f7af407b8464486a9bd064fab'
README_SERVICE=b'[Unit]\nDescription=Day-bounded R2D2 V2 shadow reader\nWants=network-online.target\nRequires=docker.service\nAfter=network-online.target docker.service\nRequiresMountsFor=@HOST_DATA_ROOT@ @HOST_JOURNAL_ROOT@ @HOST_CAPACITY_ROOT@ @HOST_CONFIG_DIR@\nStartLimitIntervalSec=8h\nStartLimitBurst=40\nOnFailure=c3po-reader-alert.service\n\n[Service]\nType=exec\nEnvironment=DOCKER_CONFIG=@HOST_CONFIG_DIR@/docker-cli\nExecCondition=/usr/bin/test -f @HOST_CONFIG_DIR@/secret.env\nExecCondition=/usr/bin/test -f @HOST_CONFIG_DIR@/pins.env\nExecCondition=/usr/bin/test -f @HOST_CONFIG_DIR@/activation.env\nExecStartPre=-/usr/bin/docker rm c3po-reader\nExecStartPre=/usr/bin/docker image inspect --format {{.Id}} @IMAGE_ID@\nExecStart=/usr/bin/docker run --rm --init --restart no --name c3po-reader --pull never \\\n  --user 0:0 --workdir /app --network @NETWORK@ \\\n  --read-only --tmpfs /tmp:rw,noexec,nosuid,nodev,size=256m \\\n  --cap-drop ALL --security-opt no-new-privileges --pids-limit 512 --stop-timeout 25 \\\n  --env-file @HOST_CONFIG_DIR@/secret.env \\\n  --env-file @HOST_CONFIG_DIR@/pins.env \\\n  --env-file @HOST_CONFIG_DIR@/activation.env \\\n  --mount type=bind,source=@HOST_DATA_ROOT@,target=/app/day-d-data,readonly \\\n  --mount type=bind,source=@HOST_JOURNAL_ROOT@,target=@CONTAINER_JOURNAL_ROOT@,readonly \\\n  --mount type=bind,source=@HOST_CAPACITY_ROOT@,target=/c3po-capacity,readonly \\\n  --mount type=bind,source=@HOST_CONFIG_DIR@/launcher,target=/c3po-reader,readonly \\\n  @IMAGE_ID@ \\\n  python -I -B /c3po-reader/reader_launcher.py\nExecStop=-/usr/bin/docker stop -t 25 c3po-reader\nExecStopPost=-/usr/bin/docker stop -t 25 c3po-reader\nRestart=on-failure\nRestartSec=5s\nRestartPreventExitStatus=78\nTimeoutStartSec=60s\nTimeoutStopSec=30s\nKillMode=control-group\nUMask=0077\nNoNewPrivileges=true\nStandardOutput=journal\nStandardError=journal\nSyslogIdentifier=c3po-reader\n'
README_TIMER_SHA256='dc81e21bfc2398330dd7eff02cbc8cf8d0e035bce883653cab4b10a1078ed4ba'
README_TIMER=b'[Unit]\nDescription=Start the approved V2 shadow reader on session days\n\n[Timer]\nOnBootSec=90s\nOnCalendar=Mon..Fri *-*-* 04:00:00 America/New_York\nOnCalendar=Mon..Fri *-*-* 09:29:20 America/New_York\nPersistent=false\nAccuracySec=1s\nUnit=c3po-reader.service\n\n[Install]\nWantedBy=timers.target\n'
README_ALERT_SHA256='0653bf416e77c5b69d66e4952468380e89b2a79d1cc38c40509332ae015cce2f'
README_ALERT=b"[Unit]\nDescription=Record that the V2 shadow reader unit entered the failed state\n\n[Service]\nType=oneshot\nUMask=0077\nExecStart=/bin/sh -c 'umask 077 && set -C && /usr/bin/systemctl show c3po-reader.service --property=Result,ExecMainCode,ExecMainStatus,NRestarts > /var/lib/c3po-reader/failed.`/usr/bin/date -u +%%Y%%m%%dT%%H%%M%%SZ`'\nStandardOutput=journal\nStandardError=journal\nSyslogIdentifier=c3po-reader-alert\n"
PRODUCER_TEMPLATE_SHA256='9e7de1c6eaf937e5b1fc9540986fdbdf2a2f821a9c57b944f9534a605d07f04a'
PRODUCER_TEMPLATE=b'[Unit]\nDescription=Bounded daily Massive minute producer\nWants=network-online.target\nRequires=docker.service\nAfter=network-online.target docker.service\nRequiresMountsFor=@HOST_JOURNAL_ROOT@ @HOST_STATE_ROOT@ @HOST_CONFIG_DIR@\nStartLimitIntervalSec=8h\nStartLimitBurst=6\n\n[Service]\nType=exec\nEnvironment=DOCKER_CONFIG=@HOST_CONFIG_DIR@/docker-cli\nExecStartPre=-/usr/bin/docker rm c3po-massive\nExecStartPre=/usr/bin/docker image inspect --format {{.Id}} @IMAGE_ID@\nExecStart=/usr/bin/docker run --rm --init --restart no --name c3po-massive --pull never \\\n  --user 0:0 --workdir /app --network @NETWORK@ \\\n  --read-only --tmpfs /tmp:rw,noexec,nosuid,nodev,size=256m \\\n  --cap-drop ALL --security-opt no-new-privileges --pids-limit 512 --stop-timeout 25 \\\n  --mount type=bind,source=@HOST_JOURNAL_ROOT@,target=@CONTAINER_JOURNAL_ROOT@ \\\n  --mount type=bind,source=@HOST_STATE_ROOT@,target=/var/lib/c3po-bar/supervisor \\\n  --mount type=bind,source=@HOST_CONFIG_DIR@,target=/etc/c3po-bar,readonly \\\n  @IMAGE_ID@ \\\n  python -B -m app.r2d2_v2_massive_supervisor --journal-root @CONTAINER_JOURNAL_ROOT@ --manifest-directory /etc/c3po-bar/manifests --token-file /etc/c3po-bar/token --state-root /var/lib/c3po-bar/supervisor\nExecStop=-/usr/bin/docker stop -t 25 c3po-massive\nExecStopPost=-/usr/bin/docker stop -t 25 c3po-massive\nRestart=on-failure\nRestartSec=1s\nRestartPreventExitStatus=78\nTimeoutStartSec=60s\nTimeoutStopSec=30s\nKillMode=control-group\nUMask=0077\nNoNewPrivileges=true\nStandardOutput=journal\nStandardError=journal\nSyslogIdentifier=c3po-massive\n'
PRODUCER_VALUES={'CONTAINER_JOURNAL_ROOT': '/c3po-bar-journal', 'HOST_CONFIG_DIR': '/etc/c3po-bar', 'HOST_JOURNAL_ROOT': '/var/lib/c3po-bar/journal', 'HOST_STATE_ROOT': '/var/lib/c3po-bar/supervisor', 'IMAGE_ID': 'sha256:f86bfb198c186657598c2c410fb39ca3dfed781d0db0522b9a796b80275cb621', 'NETWORK': 'bridge'}
PRODUCER_RENDER_SHA256='662c57b939d1a21e67e332434d3fa40368e2d503f3772f1cf3f7bd3631bdbc06'
