"""L12-HOST v3 lot SPECs of epoch 04 (Fable, Mac, offline): UP.SPEC.json filled with REAL values and the DOWN draft.

    python3 -I -B lots/build_specs.py write       -> lots/UP.SPEC.json, lots/DOWN.SPEC.DRAFT.json (refuses to overwrite)
    python3 -I -B lots/build_specs.py validate    -> both specs through bind_l12host.build_lot in PHYSICAL mode (every
                                                     v3 rule and epoch-04 guard) after replacing ONLY the declared
                                                     placeholders with synthetic fill-ins; prints the summaries.

UP (Saturday 10/10): the real image sha256:bf37cec9..., revision de96aee9..., package 43db2b96..., runner04 e9be2b30...
(full-hash name), the 11 UP plans generated by Codex's gen_k9_plans04 2b08ee13 with the REAL release 5fd6eadb... and
policy 6757e791... (lots/up_plans_DRAFT_actB_GO_pending, generated from lots/up_inputs). The rows are the generator's
manifest rows converted to the v3 CONTAINER shape (network per class, env files and emitter mount from the secrets
root REQUEST parameter). Placeholders that stay until Saturday / Codex:
    act B 04 and the K9 04 GO     -> the plan bytes (and so every plan hash) are DRAFT: regenerate with the real files
    ext/k9_verifiers04.py          -> the Codex-reviewed K9 approval/original/step verifiers (REAL, pinned)
    networks (D-NET, v3.3f)        -> DECIDED (Codex #429 6097884984): K9 PROVIDER bridge, DATABASE c3po_c3po_internal,
                                      DATABASE_AND_PROVIDER c3po_db_loopback; reader unit c3po_c3po_internal, supervisor
                                      unit c3po_db_loopback (runtime constants, pinned in physical mode; never c3po_default)
    secrets_root                   -> REQUEST parameter; default = the generator's epoch-03 root (Codex root closure:
                                      CONDITIONAL_READONLY_REUSE_MATERIAL_ONLY); INSTALL_TREE04 rev 2 also creates
                                      the epoch-04 copies under /var/lib/c3po/r2d2-v2-k9-20261012/secrets.
DOWN (Sunday 11/10, B3): e6, J (J1/J2/J3 of ONE attempt), post in the core; the late session start and the K9 capture as
EXTENDED steps; gate (bounded readback r1), capacity and READY sections. Every unknown is an @P_...@ placeholder.

Lots patch v3.4 (L-06, L-02, L-01). The in-family `write` and `validate` above are unchanged, except that the DOWN draft's
PO now starts at 06:01:30 BRT (09:01:30Z; L-02) and `validate` also reports every slot's start-window margin. The REAL
specs are written OUTSIDE the sealed family, so they never change its seal:

    python3 -I -B lots/build_specs.py write --out-dir DIR --lot UP|DOWN --plans-dir P --go F --layout L
            --secrets-root S --network PROVIDER=N --network DATABASE=N --network DATABASE_AND_PROVIDER=N
            --owner-deadline Z --values V.json
        DIR (created 0700; must not exist; never inside the family root or its sealed delivery, symlinks and case
        resolved by device/inode) receives <LOT>.SPEC.json (the bare spec `bind_l12host.py lot --spec` reads), every
        file the spec names copied byte for byte under its signed relative name, and SHA256SUMS; each file O_EXCL 0600.
        P is a gen_k9_plans04 output of an ELECTED grid (C/D/E; never DRAFT3_REJECTED, never synthetic), byte-equal to its
        manifest, with the family's runner; F is the manifest's GO (never the draft placeholder); V maps EVERY @P_...@
        placeholder of the lot to its real value (a placeholder that names a file maps to that file's absolute path);
        none may remain and no other key is accepted. Every slot's [at, at + 60 s] + 45 s must be allowed by the
        engine's start-minute rule. The spec passes bind_l12host.build_lot in PHYSICAL mode before the first write and
        again re-read from DIR. Nothing inside the family is written.
    python3 -I -B lots/build_specs.py validate --out-dir DIR --layout L
        Re-checks a written REAL dir (SHA256SUMS exact, no placeholder, elected grid, start windows, physical build_lot);
        writes nothing.

v3.3 (lots patch review: GO with condition F1, and LOW 6):
    F1  `write --lot DOWN` also needs `--up-real-dir U` (the written REAL UP dir; refused for `--lot UP`) and refuses
        before any write unless the DOWN's K9 request, GO, runner and capture_launch plan are byte-identical to the
        UP's and its grid id is the UP's (REAL_DOWN_GRID_NOT_THE_UP_ONE, REAL_DOWN_K9_REQUEST_NOT_THE_UP_ONE,
        REAL_DOWN_K9_GO_NOT_THE_UP_ONE, REAL_DOWN_RUNNER_NOT_THE_UP_ONE, REAL_DOWN_CAPTURE_PLAN_NOT_THE_UP_ONE), then
        re-validates U whole (REAL_DOWN_UP_DIR_INVALID). For that check the REAL UP dir also holds
        cross_lot/capture_launch.json, the capture_launch plan of ITS plans run (listed in its SHA256SUMS, bound by
        `validate` to its request and GO, not named by the UP spec, so `bind_l12host.py lot` never reads it).
    LOW 6  `validate --out-dir` takes a relative DIR as `write` does (made absolute); a DIR that is not a directory is
        REAL_SPEC_DIR_NOT_A_DIRECTORY.

v3.3f (Codex D-NET, L2, K9 REAL files, KILL ruling, GO form):
    D-NET  NETWORKS are the runtime's K9_NETWORKS_EPOCH04; the session units take READER_NETWORK_EPOCH04 /
        SUPERVISOR_NETWORK_EPOCH04 (each its own constant; build_down no longer reuses the DATABASE class for both).
        `write` refuses any other --network value (REAL_NETWORKS_NOT_DNET); the runtime pins all five in physical mode.
    REAL   `write --out-dir` takes the REAL K9 files as explicit inputs and copies them byte for byte into DIR and
        SPEC.files (refusing a missing, unknown or unbound one BEFORE any write):
            --k9-verifier F --k9-verifier-sha256 HEX     ext/k9_verifiers04.py (Codex sealed source; sha256 = the flag)
            --k9-policy F                                k9/VERIFIER_POLICY_04.json (this lot's registry)
            --k9-review F                                k9/CURRENT_CODEX_K9_VERIFIER_REVIEW.json
            --k9-publication F                           k9/K9_GO_04.PUBLICATION.json
            --k9-original NAME=F (one per name)          the verifier's ORIGINAL_PINS, each at the registry's path
        The verifier's three callbacks (verify_approval / verify_original / verify_step) are the K9 external rows;
        its APPROVED_REGISTRY_PINS must seal this lot's registry; the registry binds the review, publication, GO,
        request, grid, the eight originals and all 12 plans and derived effect rows. The DOWN write also requires the
        UP dir's verifier, review, publication, originals and records byte-identical and the two registries equal
        except `lot` (F1, extended). A placeholder of the verifier in the values map is refused (it is a flag now).
    KILL   `write` also writes records/K9_04_STEP_SET_MANIFEST.json (the generator manifest of the plans run) and
        records/KILL_CHANGED_ROWS.json (L12HOST_K9_KILL_CHANGED_ROWS_V1: for all 12 rows the generator row and its
        sha256, the new exact row and its sha256, the transport, the timeout derivation min(generator, budget - 65) or
        the capture's kept 655, the K9 REQUEST and the provenance); `validate` re-derives it byte for byte;
        `kill-record` prints it before any REAL write (the registry must register these row hashes).

    python3 -I -B lots/build_specs.py kill-record --plans-dir P --go F --layout L --secrets-root S
            --network PROVIDER=bridge --network DATABASE=c3po_c3po_internal --network DATABASE_AND_PROVIDER=c3po_db_loopback

v3.3g (root decision on the grid-E patch review, finding 2): ELECTED_GRIDS = C/D/E. The family generator (grid-E patch
04379aa6) offers grid E as a literal table (Codex #429 6098340344 / 6098395962: documentary reserve); `write` and
`validate` now also accept a plans run of grid E. Using E still needs its own GO, originals, registry and Codex review
(no automatic migration from D). Every other rule is unchanged; for a D run the only bytes that differ from v3.3f's
writer are the KILL record's provenance builder_sha256 / generator_sha256 (these two files changed) and the SHA256SUMS
that lists it; every row_sha256 is the same.
"""
import argparse
import copy
from datetime import timedelta
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile
import types

LOTS = Path(__file__).resolve().parent
FAMILY = LOTS.parent
sys.path.insert(0, str(FAMILY / "vendor"))
sys.path.insert(0, str(FAMILY))
import l12host_runtime as rt      # noqa: E402
import l12host_effect as fx       # noqa: E402
import bind_l12host as bind       # noqa: E402

PLANS = "up_plans_DRAFT_actB_GO_pending"
DRAFT_GO = "up_inputs/K9_GO_04.PLACEHOLDER.txt"
DRAFT_ACT_B = "up_inputs/ACT_B_04.PLACEHOLDER.txt"
RUNNER = "k9tools/k9_runner04.py"
GENERATOR = "k9tools/gen_k9_plans04.py"
GEN_SECRETS_ROOT = "/var/lib/c3po/r2d2-v2-k9-20261005/secrets"
# v3.3f (Codex D-NET): the K9 class networks and the two session-unit networks are the runtime's physical pins
NETWORKS = dict(rt.K9_NETWORKS_EPOCH04)
UNIT_NETWORKS = {"reader": rt.READER_NETWORK_EPOCH04, "supervisor": rt.SUPERVISOR_NETWORK_EPOCH04}
D1 = "09de76e5a2ee54fdcdfa477b0f8df101fcda761b7f416e4308e29c0235e51c2a"
ORDER = "70cb947fc5276949ca3f08d53cfaf79873463a83f36a64859056d7616fcdf9d3"
IMAGE = "sha256:bf37cec9f4f93e129543235a567a2de5daad0c8116086e2b176069e497defba3"
REVISION = "de96aee90a26e9587663ba7a1f6e55a592afcd20"
PACKAGE = "43db2b969fe113594fafe4a9e0cabec1f80ada9f8ab9ee5852677d65e2ec716a"
RELEASE = "5fd6eadbf8c1c899598e23c52e98599fe9cc990bd33a182cc363d2c05c5784ab"
POLICY = "6757e79112770f948b73770f6b6b87f209930afe8cd00f9517d378055e0d2d92"
VERIFIERS_PLACEHOLDER = "@P_CODEX_REVIEWED_K9_VERIFIERS04_PY@"
CORE = (("prove", "prove_launch", []), ("collect", "collect_launch", ["prove"]),
        ("commit_result", "commit_launch", ["collect"]), ("publish_launch", "publish_launch", ["commit_result"]))
J4_PROGRAMS = {"hot_runtime": "55e2cc2c97c73d0b7ae9ad8289b9cf7ff28dfb26321690b5ea40cb21438921bc",
               "hot_worker": "0edb64f45b8a4e31e64aa274e778566106e3549d7e8fe2ab8d746dd1b751d8fa",
               "hot_watchdog": "12ce74398c8bb5d0a48af8d528dc40be8703860b7cd47223328cdb9e6c073def",
               "finite_batch": "809a816d4179ee889531bfc2d270e193508f0d1a31d7a30a48159151f80dbeec",
               "folder_veto": "8d63f75cad847da5d4f5ede7dedba24b64ea296d86bad67d16fb5f8e02271b18",
               "veto_emitter": "b3ea98c4e35d749946f95b32b7dbf8e726779c70fa9f5e5001572a3f24045817",
               "config_finalizer": "45dce62d7f8e17cb3d93bfefa480352778234cc9ee88c632ad9a5268b732a30d",
               "consumer_codec": "57933d7cf4d79b62ab1c7b291b8c460a743864c78d5ad5a3111c9b2c0b76f2b6",
               "j_slot": "d4c029cabf895276e81dec38f38b387be9c85f03d4e26926846d3c8c8505db04",
               "authority_bridge": "@P_J4_AUTHORITY_BRIDGE_REAL_SHA256@"}
# L-02 / L-01 (Codex P4 ruling): a slot may start up to at + LATE_SECONDS and a K9 row reaches its effect up to 45 s
# after its instant; [at, at + 60 s] + 45 s must lie wholly before the engine's next forbidden second.
EFFECT_LEAD_SECONDS = 45
START_WINDOW_SECONDS = rt.LATE_SECONDS + EFFECT_LEAD_SECONDS
ELECTED_GRIDS = ("C", "D", "E")          # v3.3g: E admitted by the REAL writer (root decision); C/D unchanged
NETWORK_CLASSES = ("PROVIDER", "DATABASE", "DATABASE_AND_PROVIDER")


class Refused(rt.Hold):
    """A refusal of the REAL writer; `detail` names the offending item (never a secret)."""

    def __init__(self, code, detail=None):
        super().__init__(code)
        self.detail = detail


def refuse(ok, code, detail=None):
    if not ok:
        raise Refused(code, detail)


def z(text):
    return text.replace("+00:00", "Z")


def at_minus(text, seconds):
    return rt.iso(rt.stamp(z(text)) - timedelta(seconds=seconds))


def at_plus(text, seconds):
    return rt.iso(rt.stamp(z(text)) + timedelta(seconds=seconds))


def manifest(plans=PLANS):
    """The generator manifest of a plans directory (relative to lots/, or absolute for a REAL one)."""
    return json.loads((LOTS / plans / "K9_04_STEP_SET_MANIFEST.json").read_bytes())


DOCKER_MARGIN = 20                        # l12host_effect.DOCKER_MARGIN_SECONDS
SLACK_KILL = DOCKER_MARGIN + rt.GATE_ALLOWANCE_SECONDS + rt.EFFECT_LATENESS_SLACK_SECONDS     # 65 s


def kill_with_slack(step):
    """v3.1 (finding 8): the inner KILL of an UP row leaves >= 30 s of slack beyond (effect floor + gate allowance):
    KILL = min(generator KILL, budget - 20 - 15 - 30). For a LAUNCH step the generator's KILL is budget - 35 (the
    runner stops itself at run_not_after - 60 = start + budget - 90 and has < 55 s to write its DEADLINE receipt);
    with KILL = budget - 65 that window is 25 s + the effect lateness (Codex ruling requested; CONTRACT 9.3)."""
    return min(step["l12_effect"]["docker"]["timeout_seconds"], step["budget_seconds"] - SLACK_KILL)


def convert(step, secrets_root, networks, *, slack=True):
    """The generator's K9STEP row (v1 shape) -> the v3 CONTAINER row: network per class, env files and the emitter
    mount re-rooted at the secrets root parameter, receipt FILE, no `mode` (ATTACHED is the only mode). v3.1: UP rows
    get the slack KILL (kill_with_slack); the DOWN capture keeps the generator's KILL (its shell ceiling 750 s is above
    the plan budget 690 s and already leaves 30 s)."""
    e = step["l12_effect"]
    d = e["docker"]
    swap = lambda p: secrets_root + p[len(GEN_SECRETS_ROOT):] if p.startswith(GEN_SECRETS_ROOT + "/") else p
    cls = step["network_class"]
    return {"kind": "CONTAINER", "docker": {
        "name": d["name"], "labels": d["labels"], "network": "none" if cls == "NONE" else networks[cls],
        "env_files": [swap(p) for p in d["env_files"]], "env": d["env"],
        "mounts": [dict(m, source=swap(m["source"])) for m in d["mounts"]], "tmpfs": d["tmpfs"], "workdir": d["workdir"],
        "image_id": d["image_id"], "command": d["command"],
        "timeout_seconds": kill_with_slack(step) if slack else d["timeout_seconds"]},
        "receipt": {"source": "FILE", "path": e["receipt"]["path"]}}


# v3.3f (Codex ADDENDUM 8_KILL): the KILL of every current K9 row and the own changed-row record that enumerates it
KILL_RECORD = "records/KILL_CHANGED_ROWS.json"
MANIFEST_RECORD = "records/K9_04_STEP_SET_MANIFEST.json"
KILL_RECORD_SCHEMA = "L12HOST_K9_KILL_CHANGED_ROWS_V1"
KILL_FORMULA = "min(generator_timeout_seconds, budget_seconds - 65); 65 = 20 docker margin + 15 gate allowance + 30 lateness slack"
KILL_CAPTURE_RULE = "DOWN capture_launch keeps its generator timeout (655) under the shell ceiling 750 s and the plan budget 690 s"
KILL_RULING = "Codex ADDENDUM 8_KILL APPROVE_FORM_MIN_GENERATOR_KILL_BUDGET_MINUS65_FOR_CURRENT_CANDIDATE_ROWS_ONLY"


def k9_rows(m, secrets_root, networks):
    """{runner operation: {target, target_kind, slot, lot, row}} of ALL 12 steps of a plans run, in manifest order: the
    11 UP rows with the slack KILL and the DOWN capture with the generator's (the rows build_up/build_down sign)."""
    slots = {r["operation"]: r["slot"] for r in m["grid"]["slots"]} if type(m.get("grid")) is dict else {}
    targets = {op: ("CORE", core) for core, op, _ in CORE}
    targets.update({op: ("EXTENDED", name) for name, (_, op, _) in rt.EXTENDED_TABLE["UPSTREAM_P"].items()})
    targets["capture_launch"] = ("EXTENDED", "capture_launch")
    return {op: {"target": targets[op][1], "target_kind": targets[op][0], "slot": slots.get(op), "lot": step["lot"],
                 "row": convert(step, secrets_root, networks, slack=op != "capture_launch")}
            for op, step in m["steps"].items()}


def kill_record(m, manifest_raw, secrets_root, networks, lay):
    """The canonical L12HOST_K9_KILL_CHANGED_ROWS_V1 bytes of a plans run: per row the generator row (v1 shape) and its
    sha256, the new exact CONTAINER row and its sha256 (= the K9 decoder's provenance binding and the registry's
    effect_sha256), every changed field, the transport (the engine's docker argv for the layout, attempt key and L12
    REQUEST left symbolic), the timeout derivation; the K9 REQUEST and the provenance. Writes nothing."""
    engine = (FAMILY / "l12host_effect.py").read_bytes()
    rows = []
    for op, entry in k9_rows(m, secrets_root, networks).items():
        step, row = m["steps"][op], entry["row"]
        gen = step["l12_effect"]
        gen_t, budget, kill = gen["docker"]["timeout_seconds"], step["budget_seconds"], row["docker"]["timeout_seconds"]
        capture = op == "capture_launch"
        changes = [["kind", gen.get("kind"), row["kind"]]] if gen.get("kind") != row["kind"] else []
        for key in sorted(set(gen["docker"]) | set(row["docker"])):
            old, new = gen["docker"].get(key, "<absent>"), row["docker"].get(key, "<absent>")
            if old != new:
                changes.append(["docker." + key, old, new])
        if gen.get("receipt") != row["receipt"]:
            changes.append(["receipt", gen.get("receipt"), row["receipt"]])
        rows.append({
            "operation": op, "target": entry["target"], "target_kind": entry["target_kind"], "slot": entry["slot"],
            "lot": entry["lot"], "plan_sha256": step["plan_sha256"], "budget_seconds": budget,
            "generator_row": gen, "generator_row_sha256": rt.sha(rt.canonical(gen)), "generator_timeout_seconds": gen_t,
            "timeout_rule": "CAPTURE_GENERATOR_KILL_KEPT" if capture else "MIN_GENERATOR_BUDGET_MINUS_65",
            "derivation": ("generator %d kept (plan budget %d s, shell ceiling 750 s)" % (gen_t, budget) if capture
                           else "min(%d, %d - %d) = %d" % (gen_t, budget, SLACK_KILL, kill)),
            "timeout_seconds": kill, "timeout_changed": kill != gen_t, "changes": changes,
            "row": row, "row_sha256": rt.sha(rt.canonical(row)),
            "transport": {"effect_kind": "CONTAINER", "engine_mode": "ATTACHED", "engine_sha256": rt.sha(engine),
                          "inner_kill_seconds": kill, "docker_margin_seconds": DOCKER_MARGIN,
                          "effect_floor_seconds": kill + DOCKER_MARGIN,
                          "argv": fx.docker_argv(row, lay, "<L12_ATTEMPT_KEY>", "<L12_REQUEST_SHA256>")}})
    return rt.canonical({
        "schema": KILL_RECORD_SCHEMA, "formula": KILL_FORMULA, "capture_rule": KILL_CAPTURE_RULE, "ruling": KILL_RULING,
        "request": {"k9_request_sha256": m["request_sha256"], "grid": m["grid"]["id"],
                    "grid_slots_sha256": m["grid"]["slots_sha256"]},
        "go_sha256": m["go_sha256"],
        "provenance": {"derived_by": "FABLE lots/build_specs.py v3.3f (a derivation; no Codex approval implied)",
                       "builder_sha256": rt.sha(Path(__file__).read_bytes()),
                       "generator_sha256": rt.sha((LOTS / GENERATOR).read_bytes()),
                       "generator_manifest_sha256": rt.sha(manifest_raw), "runner_sha256": m["runner"]["sha256"],
                       "layout_sha256": rt.sha(rt.canonical(lay)), "networks": dict(networks), "secrets_root": secrets_root},
        "rows": rows})


def slack_table(spec):
    """budget floor vs effect lateness of every K9 row of a spec (CONTRACT 9.3)."""
    rows = []
    for t in spec["tasks"]:
        d = t["effect"].get("docker")
        if d:
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": t["operation"], "budget": t["budget_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": t["budget_seconds"] - floor,
                         "slack_beyond_allowance": t["budget_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS})
    for s in (spec["extended"] or {}).get("steps", []):
        d = (s["effect"] or {}).get("docker")
        if d:
            extra = 2 * rt.GATE_ALLOWANCE_SECONDS if s["step"] == "capture_launch" else 0
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": s["step"], "budget": s["ceiling_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": s["ceiling_seconds"] - floor - extra,
                         "slack_beyond_allowance": s["ceiling_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS - extra})
    return rows


def start_margin(at, horizon=6 * 3600):
    """Seconds from the instant `at` to the first second the ENGINE's start-minute rule refuses."""
    for k in range(horizon):
        if fx.start_minute_violation(at + timedelta(seconds=k)) is not None:
            return k
    return horizon


def start_windows(spec):
    """Every slot of a spec, by instant: its margin to the engine's next forbidden second and whether the whole
    [at, at + 60 s] + 45 s is allowed (margin > 105 s)."""
    rows = []
    for owner in list(spec["tasks"]) + list((spec["extended"] or {}).get("steps", [])):
        for s in owner["slots"]:
            at = rt.stamp(s["at"], rt.Hold)
            margin = start_margin(at)
            rows.append({"slot": s["slot"], "target": owner.get("operation") or owner.get("step"), "at": s["at"],
                         "brt": at.astimezone(rt.BRT).strftime("%a %d/%m %H:%M:%S"), "margin_seconds": margin,
                         "needed_seconds": START_WINDOW_SECONDS + 1, "ok": margin > START_WINDOW_SECONDS})
    return sorted(rows, key=lambda r: r["at"])


def k9_decoder(op, row, nb, na, mode="REAL"):
    return {"kind": "K9_STEP_V1", "mode": mode, "runner_source": "ext/k9_runner04.py", "step_plan": "k9/%s.json" % op,
            "k9_request": "k9/K9_04_STEP_SET_REQUEST.json", "k9_go": "k9/K9_GO_04.json",
            "provenance_binding_sha256": rt.sha(rt.canonical(row)), "phase_not_before": nb, "phase_not_after": na,
            "verifiers": {"approval": "k9_approval", "original": "k9_original"}}


def k9_files(ops, plans=PLANS, go=DRAFT_GO):
    files = {"ext/k9_runner04.py": RUNNER,
             "k9/K9_04_STEP_SET_REQUEST.json": plans + "/K9_04_STEP_SET_REQUEST.json",
             "k9/K9_GO_04.json": go,
             "ext/k9_verifiers04.py": VERIFIERS_PLACEHOLDER}
    for op in ops:
        files["k9/%s.json" % op] = plans + "/plans/%s.json" % op
    return files


def k9_section(ops, secrets_root, networks):
    return {"runner_source": "ext/k9_runner04.py", "request": "k9/K9_04_STEP_SET_REQUEST.json", "go": "k9/K9_GO_04.json",
            "plans": {op: "k9/%s.json" % op for op in ops}, "networks": dict(networks), "secrets_root": secrets_root}


K9_EXTERNAL = {"k9_approval": {"file": "ext/k9_verifiers04.py", "identity": "verify_approval"},
               "k9_original": {"file": "ext/k9_verifiers04.py", "identity": "verify_original"},
               "k9_step": {"file": "ext/k9_verifiers04.py", "identity": "verify_step"}}


# ------------------------------------------------------------------ UP
def build_up(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS, *, plans=PLANS, go=DRAFT_GO,
             owner_deadline="2026-10-10T13:20:00Z"):
    m = manifest(plans)
    steps = m["steps"]
    tasks, ops = [], []
    for i, (core, op, requires) in enumerate(CORE):
        s = steps[op]
        start = z(s["starts_at_utc"])
        nb, na = at_minus(start, 30), at_plus(start, s["budget_seconds"])
        row = convert(s, secrets_root, networks)
        tasks.append({"operation": core, "not_before": nb, "not_after": na, "budget_seconds": s["budget_seconds"],
                      "requires": requires, "slots": [{"slot": "P%d" % (i + 1), "at": start}], "effect": row,
                      "decoder": k9_decoder(op, row, nb, na), "image_go_sha256": None, "image_proposal_sha256": None})
        ops.append(op)
    ext = []
    for j, (name, (kind, op, requires)) in enumerate(rt.EXTENDED_TABLE["UPSTREAM_P"].items()):
        s = steps[op]
        start = z(s["starts_at_utc"])
        ext.append({"step": name, "not_before": at_minus(start, 30), "not_after": at_plus(start, s["budget_seconds"]),
                    "ceiling_seconds": s["budget_seconds"], "requires": [list(r) for r in requires],
                    "effect": convert(s, secrets_root, networks), "decoder": {"kind": "K9_EXT_STEP_V3", "verifier": "k9_step"},
                    "pre_effect": None, "hold_until": None, "slots": [{"slot": "X%d" % (j + 1), "at": start}]})
        ops.append(op)
    return {"schema": bind.SPEC_SCHEMA, "lot": "UP", "lane": "UPSTREAM_P", "mode": "REAL",
            "owner_deadline": owner_deadline, "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {}, "imports": {}, "files": k9_files(ops, plans, go), "external": dict(K9_EXTERNAL),
            "k9": k9_section(ops, secrets_root, networks), "tasks": tasks, "extended": {"steps": ext},
            "bootstrap": None, "gate": None, "capacity": None, "ready": None, "j4": None}


# ------------------------------------------------------------------ DOWN (draft, B3)
def layout():
    return bind.loose_json(LOTS / "layout.e04.DRAFT.json")


# L-02 (lots patch v3.4): PO starts at 06:01:30 BRT, 30 s after E6 (06:01:00) and long before J1 (07:38:00). Its whole
# [at, at + 60 s] + 45 s ends 06:03:15, 25 s before the engine's first forbidden second 06:03:40 (margin 130 s; the
# former 06:03:00 had 40 s). Window [at - 30 s, at + 120 s), budget 60 s: the shape of the former slot.
PO_AT, PO_NOT_BEFORE, PO_NOT_AFTER = "2026-10-12T09:01:30Z", "2026-10-12T09:01:00Z", "2026-10-12T09:03:30Z"


def build_down(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS, *, plans=PLANS, go=DRAFT_GO, lay=None,
               owner_deadline="2026-10-12T00:44:00Z"):
    m = manifest(plans)
    lay = layout() if lay is None else lay
    docker = lay["binaries"]["docker"]
    reader, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-reader.service"), {
        "@HOST_DATA_ROOT@": "/mnt/day-d-data", "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT,
        "@HOST_CAPACITY_ROOT@": rt.EPOCH04_CAPACITY_ROOT, "@HOST_CONFIG_DIR@": rt.EPOCH04_READER_CONFIG,
        "@IMAGE_ID@": IMAGE, "@NETWORK@": UNIT_NETWORKS["reader"], "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.READER_NAME, "SESSION_READER", lay, [("c3po-reader", rt.READER_NAME)])
    sup_cfg = rt.EPOCH04_READER_CONFIG + "/supervisor"
    # v3.3f (D-NET): each unit its own network constant (was networks["DATABASE"] for both)
    supervisor, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-massive.service"), {
        "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT, "@HOST_STATE_ROOT@": rt.EPOCH04_SUPERVISOR_STATE,
        "@HOST_CONFIG_DIR@": sup_cfg, "@IMAGE_ID@": IMAGE, "@NETWORK@": UNIT_NETWORKS["supervisor"],
        "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.SUPERVISOR_NAME, "SUPERVISOR", lay,
        [("c3po-massive", rt.SUPERVISOR_NAME), ("DOCKER_CONFIG=" + sup_cfg + "/docker-cli", "DOCKER_CONFIG=" + lay["docker_config"])])
    cap = m["steps"]["capture_launch"]
    cap_start = z(cap["starts_at_utc"])
    cap_row = convert(cap, secrets_root, networks, slack=False)
    cap_nb, cap_na = at_minus(cap_start, 30), at_plus(cap_start, 750)
    task = lambda op, slots, req, eff, dec, nb, na, budget: {
        "operation": op, "not_before": nb, "not_after": na, "budget_seconds": budget, "requires": req,
        "slots": slots, "effect": eff, "decoder": dec, "image_go_sha256": None, "image_proposal_sha256": None}
    j_argv = ["--registry-record-base64", rt.J4_REGISTRY_TOKEN, "--mode", "REAL"]
    tasks = [
        task("e6", [{"slot": "E6", "at": "2026-10-12T09:01:00Z"}], ["commit_result", "publish_launch"],
             {"kind": "READBACK", "files": [{"path": "@P_E6_DOCUMENT_PATH@", "sha256": "@P_E6_DOCUMENT_SHA256@",
                                             "mode": 256, "uid": 0}]},
             {"kind": "READBACK_V3"}, "2026-10-12T09:00:30Z", "2026-10-12T09:03:00Z", 60),
        task("admission_manifest", [{"slot": "J1", "at": "2026-10-12T10:38:00Z"}, {"slot": "J2", "at": "2026-10-12T10:41:00Z"},
                                    {"slot": "J3", "at": "2026-10-12T10:44:00Z"}], ["e6"],
             {"kind": "HOST_PROGRAM", "source": "ext/j4_hot_worker.py", "argv": j_argv},
             {"kind": "HOT_J_V1", "verifier": "j4_codec"}, "2026-10-12T10:37:30Z", "2026-10-12T10:50:00Z", 300),
        task("post", [{"slot": "PO", "at": PO_AT}], ["publish_launch"],
             {"kind": "CHAIN_READBACK", "source_lot": "UP", "source_request_sha256": "@P_UP_REQUEST_SHA256@",
              "source_bound_sha256": "@P_UP_BOUND_SHA256@", "steps": list(rt.EXTENDED_TABLE["UPSTREAM_P"])},
             {"kind": "CHAIN_READBACK_V3"}, PO_NOT_BEFORE, PO_NOT_AFTER, 60)]
    steps = [
        # v3.1 (finding 2): the early read-only absence check of the ready file, 09:30 BRT (a person has ~1 h to clear
        # a leftover before the 10:29:02 BRT session start, which re-checks absence itself before the supervisor).
        {"step": "ready_check", "not_before": "2026-10-12T12:29:30Z", "not_after": "2026-10-12T12:40:00Z",
         "ceiling_seconds": 60, "requires": [], "effect": None, "decoder": {"kind": "READY_ABSENT_V3"},
         "pre_effect": None, "hold_until": None, "slots": [{"slot": "R0", "at": "2026-10-12T12:30:00Z"}]},
        {"step": "session_start", "not_before": "2026-10-12T13:28:30Z", "not_after": "2026-10-12T13:36:30Z",
         "ceiling_seconds": 420, "requires": [["core", "admission_manifest"], ["core", "post"]], "effect": reader,
         "decoder": {"kind": "SESSION_START_V3", "verifier": "session_verifier"}, "pre_effect": supervisor,
         "hold_until": "2026-10-12T13:30:30Z", "slots": [{"slot": "S1", "at": "2026-10-12T13:29:02Z"}]},
        {"step": "capture_launch", "not_before": cap_nb, "not_after": cap_na, "ceiling_seconds": 750,
         "requires": [["core", "post"], ["step", "session_start"]], "effect": cap_row,
         "decoder": k9_decoder("capture_launch", cap_row, cap_nb, cap_na), "pre_effect": None, "hold_until": None,
         "slots": [{"slot": "C1", "at": cap_start}]}]
    files = k9_files(["capture_launch"], plans, go)
    files.update({"ext/j4_hot_worker.py": "../vendor/j4_hot_worker.py", "ext/j4_codec.py": "@P_CODEX_J4_RECEIPT_CODEC_PY@",
                  "ext/session_verifier.py": "@P_CODEX_REVIEWED_SESSION_START_VERIFIER_PY@",
                  "ext/c6_bridge.py": "@P_CODEX_REVIEWED_C6_SNAPSHOT_READER_VERIFIER_PY@",
                  "ext/capacity_verifiers.py": "@P_CODEX_REVIEWED_CAPACITY_VERIFIERS_PY@",
                  "ext/ready_verifiers.py": "@P_CODEX_REVIEWED_READY_VERIFIERS_PY@",
                  "docs/bounded_readback_rule.json": "@P_APPROVED_BOUNDED_READBACK_RULE_JSON@"})
    external = dict(K9_EXTERNAL)
    external.update({"j4_codec": {"file": "ext/j4_codec.py", "identity": "verify"},
                     "session_verifier": {"file": "ext/session_verifier.py", "identity": "verify"},
                     "snapshot_reader": {"file": "ext/c6_bridge.py", "identity": "read_snapshot"},
                     "snapshot_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_snapshot"},
                     "readback_rule_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_rule"},
                     "readback_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_readback"},
                     "cap_rule": {"file": "ext/capacity_verifiers.py", "identity": "verify_rule"},
                     "cap_original": {"file": "ext/capacity_verifiers.py", "identity": "verify_original"},
                     "cap_config": {"file": "ext/capacity_verifiers.py", "identity": "verify_config"},
                     "ready_rule": {"file": "ext/ready_verifiers.py", "identity": "verify_rule"},
                     "ready_ready": {"file": "ext/ready_verifiers.py", "identity": "verify_ready"}})
    spec = {"schema": bind.SPEC_SCHEMA, "lot": "DOWN", "lane": "DOWNSTREAM_AFTER_E6", "mode": "REAL",
            "owner_deadline": owner_deadline, "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {"commit_result": "@P_UP_COMMIT_RESULT_ORIGINAL_SHA256@",
                                 "publish_launch": "@P_UP_PUBLISH_LAUNCH_ORIGINAL_SHA256@"},
            "imports": {r: {"source_lot": "UP", "request_sha256": "@P_UP_REQUEST_SHA256@",
                            "bound_sha256": "@P_UP_BOUND_SHA256@"} for r in ("commit_result", "publish_launch")},
            "files": files, "external": external, "k9": k9_section(["capture_launch"], secrets_root, networks),
            "tasks": tasks, "extended": {"steps": steps}, "bootstrap": None,
            "gate": {"scope": {"build_sha": REVISION, "image_id": IMAGE, "document_order_sha256": ORDER,
                               "release_sha256": RELEASE, "package_sha256": PACKAGE,
                               "calendar_pin_sha256": "@P_CALENDAR_PIN_SHA256@",
                               "runtime_authority_sha256": "@P_RUNTIME_AUTHORITY_SHA256@", "owner_uid": 0,
                               "manifest_directory": "@P_MANIFEST_DIRECTORY@", "session_open": "2026-10-12T13:30:00Z",
                               "not_before": "2026-10-12T10:37:30Z", "not_after": "2026-10-12T10:50:00Z",
                               "view_opens_at": "2026-10-12T10:38:00Z", "require_go_mode": "INDIVIDUAL"},
                     "journal_directory": rt.EPOCH04_JOURNAL_ROOT, "snapshot_reader": "snapshot_reader",
                     "snapshot_verifier": "snapshot_verifier",
                     "readback": {"rule": "docs/bounded_readback_rule.json", "rule_verifier": "readback_rule_verifier",
                                  "readback_verifier": "readback_verifier"}},
            "capacity": {"mode": "REAL", "lots": {"m3": "BOOT", "j": "DOWN", "activation": "CAP"},
                         "sources": {"m3": "@P_M3_ACTIVATE_PROGRAM_SHA256@", "j": J4_PROGRAMS["hot_worker"],
                                     "activation": "@P_CAPACITY_MONDAY04_PROGRAM_SHA256@"},
                         "verifiers": {"rule": "cap_rule", "original": "cap_original", "config": "cap_config"},
                         "config_path": rt.EPOCH04_CAPACITY_ROOT + "/config/capacity-final-2026-10-12.json"},
            "ready": {"mode": "REAL", "calendar_sha256": "@P_CALENDAR_PIN_SHA256@", "not_before": "2026-10-12T13:29:00Z",
                      "not_after": "2026-10-12T13:29:50Z", "max_wait_seconds": 48, "poll_seconds": 0.25,
                      "ready_path": rt.EPOCH04_READY_PATH, "verifiers": {"rule": "ready_rule", "ready": "ready_ready"}},
            "j4": {"protocol": "WARM_IMAGE10_ACTUAL_OBSERVATION", "hot_worker_source": "ext/j4_hot_worker.py",
                   "programs": dict(J4_PROGRAMS),
                   "originals": {n: "@P_J4_ORIGINAL_%s_SHA256@" % n.upper()
                                 for n in sorted(set(rt.J4_ORIGINALS) - set(rt.J4_LOT_ORIGINALS))},
                   "bridge": {"bootstrap": "bootstrap", "authorize": "authorize", "general_read": "general_read",
                              "general_verify": "general_verify"},
                   "general_authority_sha256": "@P_J4_GENERAL_AUTHORITY_SHA256@",
                   "general_source_identity": "@P_J4_GENERAL_SOURCE_IDENTITY@"}}
    return spec


# ------------------------------------------------------------------ write / validate (in-family DRAFTs)
def render(spec, comment):
    """The bytes `write` puts into lots/ (a commented DRAFT wrapper; not the bare spec `bind lot` reads)."""
    return (json.dumps({"_comment": comment, "spec": spec}, sort_keys=True, indent=1) + "\n").encode("ascii")


def write(path, spec, comment):
    raw = render(spec, comment)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        os.write(fd, raw)
    finally:
        os.close(fd)
    return rt.sha(raw)


def placeholders(value, out=None):
    out = set() if out is None else out
    if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
        out.add(value)
    elif isinstance(value, dict):
        for v in value.values():
            placeholders(v, out)
    elif isinstance(value, list):
        for v in value:
            placeholders(v, out)
    return out


SYNTHETIC_MODULE = b'''"""SYNTHETIC FILL-IN (validation of the spec shape only; never a verifier)."""
def _accept(*args):
    return None
verify = verify_approval = verify_original = verify_step = verify_rule = verify_readback = _accept
verify_config = verify_ready = verify_snapshot = read_snapshot = _accept
'''


def fill(spec, tmp):
    """Replace ONLY the declared @P_...@ placeholders with synthetic values (files -> synthetic bytes in tmp)."""
    spec = copy.deepcopy(spec)
    module = Path(tmp) / "synthetic_module.py"
    module.write_bytes(SYNTHETIC_MODULE)
    doc = Path(tmp) / "synthetic_doc.json"
    doc.write_bytes(b'{"synthetic":true}')
    for rel, local in list(spec["files"].items()):
        if local.startswith("@P_"):
            spec["files"][rel] = str(module if rel.endswith(".py") else doc)
    values = {"@P_MANIFEST_DIRECTORY@": "/var/lib/c3po-capacity-e04/payload",
              "@P_E6_DOCUMENT_PATH@": "/var/lib/c3po/r2d2-v2-k9-20261012/e6/E6_04.json",
              "@P_J4_GENERAL_SOURCE_IDENTITY@": "SYNTHETIC_FILL_IN"}

    def walk(value):
        if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
            return values.get(value, hashlib.sha256(value.encode("ascii")).hexdigest())
        if isinstance(value, dict):
            return {k: walk(v) for k, v in value.items()}
        if isinstance(value, list):
            return [walk(v) for v in value]
        return value
    filled = walk(spec)
    # v3.3f: the REAL K9 files are not part of the in-family DRAFTs (only `write --out-dir` takes them); a physical
    # validation of a DRAFT with a K9 section gets SYNTHETIC fill-ins bound to the filled spec.
    return synthetic_real_k9(filled, tmp, LOTS) if filled["k9"] is not None else filled


# ------------------------------------------------------------------ v3.3f: SYNTHETIC REAL K9 files (never REAL inputs)
# The names of Codex R2's ORIGINAL_PINS (ext/k9_verifiers04.py 0e7ce65e...); the REAL writer takes them from the
# supplied verifier itself. Used here ONLY to shape synthetic fill-ins and test fixtures.
ORIGINAL_NAMES = ("act_b", "B_CODEX", "B_FABLE", "B_DUDU", "ACTA_DUDU", "template_file", "release", "policy")
SYNTHETIC_MARK = "SYNTHETIC_NOT_CODEX_NOT_AN_ORIGINAL"
PUBLICATION_KEYS = {"schema", "original_sha256", "comment_id", "author_id", "author_login", "created_at", "updated_at",
                    "published_at", "body_sha256", "prepared_body_sha256", "POST_body_sha256", "GET1_body_sha256",
                    "GET2_body_sha256", "REAL_body_sha256"}
PUBLICATION_BODIES = ("prepared_body_sha256", "POST_body_sha256", "GET1_body_sha256", "GET2_body_sha256", "REAL_body_sha256")


def synthetic_k9_verifier(original_pins, allowlist):
    """A SYNTHETIC ext/k9_verifiers04.py with the R2 literal ABI (relative names, ORIGINAL_PINS, APPROVED_REGISTRY_PINS)
    and three accepting callbacks. Never a verifier; FIXTURE/fill-in bytes only (the Linux proof's synthetic lot too)."""
    return ('"""%s: synthetic stand-in of Codex ext/k9_verifiers04.py (shape only; accepts everything)."""\n'
            "POLICY_REL = %s\nPUBLICATION_REL = %s\nCURRENT_REVIEW_REL = %s\nORIGINAL_PINS = %s\n"
            "APPROVED_REGISTRY_PINS = %s\n\n\ndef verify_approval(*args):\n    return None\n\n\n"
            "def verify_original(*args):\n    return None\n\n\ndef verify_step(*args):\n    return None\n"
            % (SYNTHETIC_MARK, json.dumps(rt.K9_REAL_POLICY), json.dumps(rt.K9_REAL_PUBLICATION),
               json.dumps(rt.K9_REAL_REVIEW), json.dumps(original_pins, sort_keys=True),
               json.dumps(allowlist, sort_keys=True))).encode("ascii")


def synthetic_originals(act_b_raw=None):
    """{name: (signed relative path, bytes)} of 8 SYNTHETIC originals; release and policy are the certified in-family
    files (their real bytes, not private), act B the given bytes (a TEST-ONLY act B) or a synthetic text."""
    out = {}
    for name in ORIGINAL_NAMES:
        if name == "release":
            raw = (LOTS / "up_inputs" / "release.CERTIFIED.04.json").read_bytes()
        elif name == "policy":
            raw = (LOTS / "up_inputs" / "policy.04.json").read_bytes()
        elif name == "act_b" and act_b_raw is not None:
            raw = act_b_raw
        else:
            raw = ("%s %s\n" % (SYNTHETIC_MARK, name)).encode("ascii")
        out[name] = ("k9/SYNTHETIC_ORIGINAL.%s.txt" % name, raw)
    return out


def synthetic_review_publication(go_sha256):
    """(review, publication) SYNTHETIC canonical bytes; the publication has the form's keys and names the GO."""
    review = rt.canonical({"schema": SYNTHETIC_MARK, "what": "stand-in of CURRENT_CODEX_K9_VERIFIER_REVIEW"})
    body = rt.sha(SYNTHETIC_MARK.encode("ascii"))
    pub = {"schema": "K9_GO_04_PUBLICATION_V1", "original_sha256": go_sha256, "comment_id": 1, "author_id": 1,
           "author_login": SYNTHETIC_MARK, "created_at": "2026-10-10T12:00:00Z", "updated_at": "2026-10-10T12:00:00Z",
           "published_at": "2026-10-10T12:00:00Z", "body_sha256": body}
    pub.update({k: body for k in PUBLICATION_BODIES})
    return review, rt.canonical(pub)


def synthetic_policy(lot, *, review, publication, go_sha256, request_sha256, grid, originals, operations):
    return rt.canonical({"schema": rt.K9_REAL_POLICY_SCHEMA, "mode": "REAL", "reviewer": SYNTHETIC_MARK,
                         "review_decision_sha256": rt.sha(review), "epoch": "R2D2-V2-SHADOW-2026-10-12",
                         "day": "2026-10-12", "lot": lot, "go_sha256": go_sha256,
                         "publication_sha256": rt.sha(publication), "request_sha256": request_sha256, "grid": grid,
                         "originals": {n: {"file": rel, "sha256": rt.sha(raw)} for n, (rel, raw) in originals.items()},
                         "operations": operations})


def synthetic_real_k9(spec, directory, base):
    """A copy of `spec` with SYNTHETIC REAL K9 files bound to it (verifier, registry of this lot, review, publication,
    8 originals) written into `directory` and named in its files; the K9 callbacks wired to the verifier's three
    functions. Every byte says SYNTHETIC; Codex's verifier would refuse all of it (unsealed, not CODEX)."""
    spec = copy.deepcopy(spec)
    directory = Path(directory)
    k9 = spec["k9"]
    local = lambda rel: Path(spec["files"][rel]) if Path(spec["files"][rel]).is_absolute() else Path(base) / spec["files"][rel]
    request, go = local(k9["request"]).read_bytes(), local(k9["go"]).read_bytes()
    grid = json.loads(request).get("grid")
    originals = synthetic_originals()
    review, publication = synthetic_review_publication(rt.sha(go))
    spec["external"].update({name: {"file": rt.K9_REAL_VERIFIER, "identity": identity}
                             for name, identity in rt.K9_REAL_CALLBACKS.items()})
    for owner in list(spec["tasks"]) + list((spec["extended"] or {}).get("steps", [])):
        if owner["decoder"] and owner["decoder"].get("kind") == "K9_STEP_V1":
            owner["decoder"]["verifiers"] = {"approval": "k9_approval", "original": "k9_original"}
        elif owner["decoder"] and owner["decoder"].get("kind") == "K9_EXT_STEP_V3":
            owner["decoder"]["verifier"] = "k9_step"
    rows = rt.k9_effect_rows({"effects": {t["operation"]: t["effect"] for t in spec["tasks"]},
                              "extended": spec["extended"]}, spec["lane"])
    operations = {op: {"phase": SYNTHETIC_MARK, "phase_row": {}, "plan_sha256": rt.sha(local(rel).read_bytes()),
                       "effect_sha256": rt.sha(rt.canonical(rows[op]))} for op, rel in k9["plans"].items()}
    policy = synthetic_policy(spec["lot"], review=review, publication=publication, go_sha256=rt.sha(go),
                              request_sha256=rt.sha(request), grid=grid.get("id") if type(grid) is dict else None,
                              originals=originals, operations=operations)
    verifier = synthetic_k9_verifier({n: rt.sha(raw) for n, (_, raw) in originals.items()}, {spec["lot"]: rt.sha(policy)})
    for rel, raw in [(rt.K9_REAL_VERIFIER, verifier), (rt.K9_REAL_POLICY, policy), (rt.K9_REAL_REVIEW, review),
                     (rt.K9_REAL_PUBLICATION, publication)] + list(originals.values()):
        path = directory / ("SYNTHETIC_FILE_" + rel.replace("/", "_"))
        path.write_bytes(raw)
        spec["files"][rel] = str(path)
    return spec


def synthetic_real_inputs(directory, plans_dir, *, act_b_raw, secrets_root=GEN_SECRETS_ROOT, networks=None):
    """TEST FIXTURE (SYNTHETIC): the REAL-writer inputs of one plans run, the way Codex's construction shapes them: 8
    originals (release/policy = the certified in-family files, act B = the plans run's TEST-ONLY act B, the others
    synthetic), a review, a publication of the run's GO, the UP and DOWN registries (all 12 plans and derived rows,
    equal except `lot`) and ONE verifier sealing both. Returns the write_real `real_k9` of each lot."""
    directory = Path(directory)
    directory.mkdir(mode=0o700)
    m = manifest(str(plans_dir))
    originals = synthetic_originals(act_b_raw)
    paths = {}
    for name, (rel, raw) in originals.items():
        paths[name] = directory / ("original." + name)
        paths[name].write_bytes(raw)
    review, publication = synthetic_review_publication(m["go_sha256"])
    rows = k9_rows(m, secrets_root, networks or NETWORKS)
    operations = {op: {"phase": SYNTHETIC_MARK, "phase_row": {}, "plan_sha256": m["steps"][op]["plan_sha256"],
                       "effect_sha256": rt.sha(rt.canonical(rows[op]["row"]))} for op in m["steps"]}
    policies = {lot: synthetic_policy(lot, review=review, publication=publication, go_sha256=m["go_sha256"],
                                      request_sha256=m["request_sha256"], grid=(m.get("grid") or {}).get("id"),
                                      originals=originals, operations=operations) for lot in ("UP", "DOWN")}
    verifier = synthetic_k9_verifier({n: rt.sha(raw) for n, (_, raw) in originals.items()},
                                     {lot: rt.sha(raw) for lot, raw in policies.items()})
    files = {"verifier": verifier, "review": review, "publication": publication, "policy-UP": policies["UP"],
             "policy-DOWN": policies["DOWN"]}
    for name, raw in files.items():
        (directory / (name + ".SYNTHETIC")).write_bytes(raw)
    common = {"verifier": str(directory / "verifier.SYNTHETIC"), "verifier_sha256": rt.sha(verifier),
              "review": str(directory / "review.SYNTHETIC"), "publication": str(directory / "publication.SYNTHETIC"),
              "originals": {n: str(p) for n, p in paths.items()}}
    return {lot: dict(common, policy=str(directory / ("policy-%s.SYNTHETIC" % lot))) for lot in ("UP", "DOWN")}


def runtime_stub(lay):
    return rt.canonical({"schema": rt.RUNTIME_SCHEMA, "layout_sha256": rt.sha(rt.canonical(lay))})


def validate_up(physical=True):
    spec = build_up()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-10T12:30:00Z", LOTS, physical=physical)
    plan = json.loads((LOTS / PLANS / "plans" / "prove_launch.json").read_bytes())
    return {"status": "UP_SPEC_VALID_WITH_FILL_INS", "physical_guards": physical, "image_id": IMAGE,
            "code_revision": plan["constants"]["code_revision"], "package_sha256": plan["constants"]["package_sha256"],
            "runner_sha256": authority["files"]["ext/k9_runner04.py"], "release_sha256": plan["constants"]["release_sha256"],
            "policy_sha256": plan["constants"]["policy_sha256"], "act_b_sha256_DRAFT": plan["constants"]["act_b_sha256"],
            "go_sha256_DRAFT": plan["go_sha256"], "slots": len(authority["slots"]), "slack": slack_table(spec),
            "start_windows": start_windows(spec),
            "placeholders": sorted(placeholders(spec)) + ["ACT_B_04 (plan constants)", "K9_GO_04 (plan go_sha256)"]}


def validate_down(physical=True):
    spec = build_down()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-11T23:00:00Z", LOTS, physical=physical)
    return {"status": "DOWN_DRAFT_VALID_WITH_FILL_INS", "physical_guards": physical,
            "session_start_at": [s for s in authority["slots"] if s["target"] == "session_start"][0]["at"],
            "ready_check_at": [s for s in authority["slots"] if s["target"] == "ready_check"][0]["at"],
            "post_at": [s for s in authority["slots"] if s["target"] == "post"][0]["at"],
            "slots": len(authority["slots"]), "slack": slack_table(spec), "start_windows": start_windows(spec),
            "placeholders": sorted(placeholders(spec))}


# ------------------------------------------------------------------ REAL specs, outside the family (L-06)
def generator():
    """The family's gen_k9_plans04 (its grid tables are the only source of the elected minutes). Executed from its
    bytes into a fresh module (its import is inert; no bytecode cache is written into the family)."""
    path = LOTS / GENERATOR
    module = types.ModuleType("gen_k9_plans04_of_the_family")
    module.__file__ = str(path)
    exec(compile(path.read_bytes(), str(path), "exec"), module.__dict__)
    return module


# v3.3 (lots review F1): the signed relative names compared between the REAL UP and the REAL DOWN, and the UP dir's
# record of the capture_launch plan of its own plans run (not named by the UP spec; listed in its SHA256SUMS).
K9_REQUEST = "k9/K9_04_STEP_SET_REQUEST.json"
K9_GO = "k9/K9_GO_04.json"
RUNNER_REL = "ext/k9_runner04.py"
DOWN_CAPTURE_PLAN = "k9/capture_launch.json"
UP_CAPTURE_ANCHOR = "cross_lot/capture_launch.json"


def same_inode(a, b):
    return (a.st_dev, a.st_ino) == (b.st_dev, b.st_ino)


def sealed_roots():
    """The family root and, when it is part of a sealed delivery (a top SHA256SUMS that lists l12host/SHA256SUMS), the
    delivery root: no REAL spec may be written under either."""
    roots = [FAMILY]
    top = FAMILY.parent / "SHA256SUMS"
    try:
        if any(line.endswith("  " + FAMILY.name + "/SHA256SUMS") for line in top.read_text("ascii").splitlines()):
            roots.append(FAMILY.parent)
    except (OSError, UnicodeDecodeError):
        pass
    return [(root, os.stat(str(root))) for root in roots]


def guard_out_dir(out_dir):
    """The REAL output directory: neither it nor any existing ancestor (symlinks resolved; compared by device and
    inode, so letter case and links cannot alias) is the family root or its sealed delivery; and it does not exist."""
    target = Path(os.path.abspath(str(out_dir)))
    probe = target
    while not os.path.lexists(str(probe)):
        probe = probe.parent
    real = Path(os.path.realpath(str(probe)))
    roots = sealed_roots()
    for ancestor in [real] + list(real.parents):
        here = os.stat(str(ancestor))
        for root, info in roots:
            refuse(not same_inode(here, info), "REAL_SPEC_OUT_DIR_INSIDE_FAMILY", root.name)
    refuse(probe != target, "REAL_SPEC_OUT_DIR_EXISTS")
    return target


def recheck_created(target):
    real = Path(os.path.realpath(str(target)))
    roots = sealed_roots()
    for ancestor in [real] + list(real.parents):
        here = os.stat(str(ancestor))
        refuse(all(not same_inode(here, info) for _, info in roots), "REAL_SPEC_OUT_DIR_INSIDE_FAMILY")


def read_file(path, limit=rt.LIMIT):
    p = Path(path)
    refuse(p.is_absolute() and not p.is_symlink() and p.is_file(), "REAL_INPUT_NOT_A_REGULAR_FILE", p.name)
    raw = p.read_bytes()
    refuse(0 < len(raw) <= limit, "REAL_INPUT_SIZE_INVALID", p.name)
    return raw


def real_plans(plans_dir, go_path):
    """The REAL K9 inputs: a gen_k9_plans04 output of an ELECTED grid, byte-equal to its manifest, with the family's
    runner, the certified release/policy, an act B that is not the draft placeholder, and the manifest's GO."""
    root = Path(plans_dir)
    refuse(root.is_absolute() and root.is_dir() and not root.is_symlink(), "REAL_PLANS_DIR_INVALID")
    m_raw = read_file(root / "K9_04_STEP_SET_MANIFEST.json")
    m = rt.strict(m_raw, kind=Refused)
    refuse(m.get("schema") == "K9_04_STEP_SET_MANIFEST_V1" and m.get("image_id") == IMAGE, "REAL_PLANS_MANIFEST_INVALID")
    refuse(m.get("synthetic") is False, "REAL_PLANS_SYNTHETIC")
    grid = m.get("grid")
    refuse(type(grid) is dict and grid.get("id") in ELECTED_GRIDS, "REAL_PLANS_GRID_NOT_ELECTED",
           grid.get("id") if type(grid) is dict else None)
    gen = generator()
    refuse(grid == gen.grid_block(grid["id"]), "REAL_PLANS_GRID_NOT_THIS_GENERATOR", grid["id"])
    request_raw = read_file(root / "K9_04_STEP_SET_REQUEST.json")
    request = rt.strict(request_raw, kind=Refused)
    refuse(rt.sha(request_raw) == m.get("request_sha256") and request.get("grid") == grid
           and request.get("synthetic") is False, "REAL_PLANS_REQUEST_NOT_THE_MANIFEST_ONE")
    table = {row["operation"]: row for row in grid["slots"]}
    refuse(type(m.get("steps")) is dict and set(m["steps"]) == set(gen.STEPS) == set(table), "REAL_PLANS_STEPS_INVALID")
    constants = None
    for op, step in m["steps"].items():
        raw = read_file(root / "plans" / (op + ".json"))
        plan = rt.strict(raw, kind=Refused)
        refuse(rt.sha(raw) == step["plan_sha256"] and plan.get("request_sha256") == m["request_sha256"]
               and plan.get("go_sha256") == m.get("go_sha256"), "REAL_PLAN_NOT_THE_MANIFEST_ONE", op)
        row = plan.get("step_row")
        refuse(type(row) is dict and row.get("grid") == grid and row.get("starts_at") == table[op]["starts_at_utc"]
               == step["starts_at_utc"], "REAL_PLAN_NOT_ON_THE_GRID", op)
        refuse(constants is None or plan.get("constants") == constants, "REAL_PLANS_CONSTANTS_DIFFER", op)
        constants = plan.get("constants")
    runner = (LOTS / RUNNER).read_bytes()
    refuse(m["runner"]["sha256"] == rt.sha(runner) and read_file(root / "tools" / m["runner"]["name"]) == runner,
           "REAL_PLANS_RUNNER_NOT_THE_FAMILY_ONE")
    refuse(constants["release_sha256"] == RELEASE and constants["policy_sha256"] == POLICY,
           "REAL_PLANS_RELEASE_POLICY_NOT_CERTIFIED")
    refuse(constants["act_b_sha256"] not in (rt.sha((LOTS / DRAFT_ACT_B).read_bytes()), gen.SYNTHETIC["act_b"]),
           "REAL_PLANS_ACT_B_IS_THE_DRAFT")
    go = read_file(go_path)
    refuse(rt.sha(go) == m.get("go_sha256"), "REAL_GO_NOT_THE_MANIFEST_ONE")
    refuse(rt.sha(go) not in (rt.sha((LOTS / DRAFT_GO).read_bytes()), rt.sha(gen.SYNTHETIC_GO)), "REAL_GO_IS_THE_DRAFT")
    return m


def substitute(spec, values):
    """Every @P_...@ of the lot from `values` (a placeholder that names a file -> that file's absolute path, its bytes
    copied at write); no other key, none left."""
    wanted = placeholders(spec)
    refuse(type(values) is dict and all(type(k) is str and type(v) is str and v and not v.startswith("@P_")
                                        for k, v in values.items()), "REAL_VALUES_INVALID")
    refuse(not set(values) - wanted, "REAL_VALUES_UNKNOWN_PLACEHOLDER", sorted(set(values) - wanted)[:1] or None)
    refuse(not wanted - set(values), "REAL_SPEC_PLACEHOLDER_UNFILLED", sorted(wanted - set(values))[:1] or None)
    file_placeholders = {v for v in spec["files"].values() if v in wanted}
    for name in file_placeholders:
        read_file(values[name])

    def walk(value):
        if isinstance(value, str) and value in wanted:
            return values[value]
        if isinstance(value, dict):
            return {k: walk(v) for k, v in value.items()}
        if isinstance(value, list):
            return [walk(v) for v in value]
        return value
    out = walk(spec)
    refuse(not placeholders(out), "REAL_SPEC_PLACEHOLDER_UNFILLED")
    return out


def validation_instant(owner_deadline):
    """prepared_at used only to validate (the REQUEST is built later by `bind_l12host.py lot --prepared-at`)."""
    return rt.iso(rt.stamp(owner_deadline, Refused) - timedelta(seconds=60))


def windows_or_refuse(spec):
    windows = start_windows(spec)
    bad = [r["slot"] for r in windows if not r["ok"]]
    refuse(not bad, "REAL_SLOT_START_WINDOW_NOT_ALLOWED", bad[:1] or None)
    return windows


def write_file(target, rel, raw):
    path = target / rel
    if path.parent != target and not path.parent.exists():
        os.mkdir(str(path.parent), 0o700)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        view = memoryview(raw)
        while view:
            view = view[os.write(fd, view):]
        os.fsync(fd)
    finally:
        os.close(fd)
    return rt.sha(raw)


# v3.3f: the REAL K9 inputs of `write` (explicit flags) and their bindings
REAL_K9_KEYS = {"verifier", "verifier_sha256", "policy", "review", "publication", "originals"}
CODEX_R2_UNSEALED_SHA256 = "0e7ce65e74dc9074ed9d3fc1724a5f57271d4503da353c85f964cd40822508e5"   # informational only


def unsealed_sha256(raw):
    """sha256 of the verifier with its ONE `APPROVED_REGISTRY_PINS = ...` line reset to the delivered `{}` (Codex's seal
    changes only that line): equal to CODEX_R2_UNSEALED_SHA256 iff the bodies are R2's. Informational, never a gate."""
    lines = raw.split(b"\n")
    hits = [i for i, line in enumerate(lines) if line.startswith(b"APPROVED_REGISTRY_PINS = ")]
    if len(hits) != 1:
        return None
    lines[hits[0]] = b"APPROVED_REGISTRY_PINS = {}"
    return rt.sha(b"\n".join(lines))


def canonical_doc(raw, code):
    try:
        return rt.strict(raw, kind=Refused)
    except rt.Hold:
        raise Refused(code) from None


def k9_real_bindings(lot, m, manifest_raw, constants, raw, secrets_root, networks, lay):
    """The REAL K9 files of one lot (`raw`: verifier, policy, review, publication bytes and {name: original bytes})
    against the plans run `m` (manifest bytes `manifest_raw`, plan `constants`): returns {signed rel: bytes} of the 11
    REAL files and the KILL record bytes. Every check here precedes any write; the runtime repeats the bindings it can
    see at bind and before every effect (validate_k9_real)."""
    source = rt.k9_real_source(raw["verifier"], Refused)
    pins = source["ORIGINAL_PINS"]
    refuse({"act_b", "release", "policy"} <= set(pins) and pins["release"] == RELEASE and pins["policy"] == POLICY
           and pins["act_b"] == constants.get("act_b_sha256"), "REAL_K9_ORIGINAL_PINS_NOT_THE_PLANS_ONES")
    refuse(set(raw["originals"]) == set(pins), "REAL_K9_ORIGINALS_NOT_THE_VERIFIER_ONES",
           sorted(set(pins) ^ set(raw["originals"]))[:1] or None)
    for name in sorted(pins):
        refuse(rt.sha(raw["originals"][name]) == pins[name], "REAL_K9_ORIGINAL_NOT_THE_PINNED_ONE", name)
    policy = canonical_doc(raw["policy"], "REAL_K9_POLICY_INVALID")
    refuse(set(policy) == rt.K9_REAL_POLICY_KEYS and policy["schema"] == rt.K9_REAL_POLICY_SCHEMA
           and policy["mode"] == "REAL" and policy["lot"] == lot and policy["epoch"] == "R2D2-V2-SHADOW-2026-10-12"
           and policy["day"] == "2026-10-12", "REAL_K9_POLICY_INVALID")
    refuse(source["APPROVED_REGISTRY_PINS"].get(lot) == rt.sha(raw["policy"]), "REAL_K9_POLICY_NOT_SEALED_IN_THE_VERIFIER")
    refuse(policy["grid"] == m["grid"]["id"] and policy["request_sha256"] == m["request_sha256"]
           and policy["go_sha256"] == m["go_sha256"], "REAL_K9_POLICY_NOT_THIS_GO_REQUEST_GRID")
    canonical_doc(raw["review"], "REAL_K9_REVIEW_INVALID")
    refuse(rt.sha(raw["review"]) == policy["review_decision_sha256"], "REAL_K9_REVIEW_NOT_THE_REGISTERED_ONE")
    pub = canonical_doc(raw["publication"], "REAL_K9_PUBLICATION_INVALID")
    refuse(rt.sha(raw["publication"]) == policy["publication_sha256"], "REAL_K9_PUBLICATION_NOT_THE_REGISTERED_ONE")
    refuse(set(pub) == PUBLICATION_KEYS and pub["schema"] == "K9_GO_04_PUBLICATION_V1"
           and pub["original_sha256"] == m["go_sha256"] and pub["created_at"] == pub["updated_at"] == pub["published_at"]
           and rt.pin(pub["body_sha256"]) and all(pub[k] == pub["body_sha256"] for k in PUBLICATION_BODIES),
           "REAL_K9_PUBLICATION_NOT_THE_GO_ONE")
    reg = policy["originals"]
    refuse(type(reg) is dict and set(reg) == set(pins) and all(
        type(r) is dict and set(r) == {"file", "sha256"} and r["sha256"] == pins[n] for n, r in reg.items()),
        "REAL_K9_POLICY_ORIGINALS_NOT_THE_VERIFIER_ONES")
    paths = [r["file"] for r in reg.values()]
    refuse(all(type(p) is str and rt.K9_REAL_ORIGINAL_REL.fullmatch(p) and p not in rt.K9_REAL_FIXED_FILES
               for p in paths) and len(set(paths)) == len(paths), "REAL_K9_ORIGINAL_PATH_INVALID")
    rows = k9_rows(m, secrets_root, networks)
    ops = policy["operations"]
    refuse(type(ops) is dict and set(ops) == set(m["steps"]), "REAL_K9_POLICY_OPERATIONS_NOT_THE_TWELVE")
    for op, step in m["steps"].items():
        refuse(type(ops[op]) is dict and ops[op].get("plan_sha256") == step["plan_sha256"],
               "REAL_K9_POLICY_PLAN_NOT_THE_MANIFEST_ONE", op)
        refuse(ops[op].get("effect_sha256") == rt.sha(rt.canonical(rows[op]["row"])),
               "REAL_K9_POLICY_EFFECT_NOT_THE_DERIVED_ROW", op)
    sources = {rt.K9_REAL_VERIFIER: ("verifier",), rt.K9_REAL_POLICY: ("policy",), rt.K9_REAL_REVIEW: ("review",),
               rt.K9_REAL_PUBLICATION: ("publication",)}
    sources.update({reg[name]["file"]: ("originals", name) for name in sorted(pins)})
    files = {rel: raw[key[0]] if len(key) == 1 else raw["originals"][key[1]] for rel, key in sources.items()}
    return files, sources, kill_record(m, manifest_raw, secrets_root, networks, lay)


def real_summary(files, sources, verifier_raw):
    """What `write` / `validate` report of the REAL K9 files (hashes and paths only, never contents)."""
    unsealed = unsealed_sha256(verifier_raw)
    return {"files": {rel: rt.sha(raw) for rel, raw in sorted(files.items())},
            "originals": {key[1]: rel for rel, key in sorted(sources.items()) if len(key) == 2},
            "verifier_sha256": rt.sha(verifier_raw), "verifier_unsealed_sha256": unsealed,
            "verifier_is_codex_r2_plus_seal": unsealed == CODEX_R2_UNSEALED_SHA256}


def real_k9_inputs(real_k9):
    """The explicit REAL K9 inputs of `write` (paths) -> bytes; the verifier's sha256 must be the flag."""
    refuse(type(real_k9) is dict and set(real_k9) == REAL_K9_KEYS and type(real_k9["originals"]) is dict,
           "REAL_K9_INPUTS_REQUIRED", sorted(REAL_K9_KEYS - set(real_k9))[:1] if type(real_k9) is dict else None)
    refuse(type(real_k9["verifier_sha256"]) is str and rt.HEX.fullmatch(real_k9["verifier_sha256"]) is not None,
           "REAL_K9_VERIFIER_SHA256_FLAG_INVALID")
    raw = {"verifier": read_file(real_k9["verifier"]), "policy": read_file(real_k9["policy"]),
           "review": read_file(real_k9["review"]), "publication": read_file(real_k9["publication"]),
           "originals": {name: read_file(path) for name, path in sorted(real_k9["originals"].items())}}
    refuse(rt.sha(raw["verifier"]) == real_k9["verifier_sha256"], "REAL_K9_VERIFIER_NOT_THE_PINNED_ONE")
    return raw


def write_real(lot, out_dir, *, plans_dir, go, layout_path, secrets_root, networks, owner_deadline, values_path,
               up_real_dir=None, real_k9=None):
    """L-06: the REAL SPEC of a lot and its files in a NEW directory outside the sealed family. v3.3 (F1): the DOWN
    needs `up_real_dir` (the written REAL UP dir) and is refused unless its K9 request, GO, runner and capture_launch
    plan bytes are the UP's and its grid id is the UP's; the UP dir records its capture_launch plan for that check.
    v3.3f: `networks` must be D-NET; `real_k9` (the explicit REAL K9 inputs) is required and bound before any write;
    the dir also gets records/ (the plans run's manifest and the KILL changed-row record)."""
    target = guard_out_dir(out_dir)
    refuse(lot in ("UP", "DOWN"), "REAL_LOT_INVALID")
    refuse(lot == "UP" or up_real_dir is not None, "REAL_DOWN_NEEDS_THE_UP_REAL_DIR")
    refuse(lot == "DOWN" or up_real_dir is None, "REAL_UP_TAKES_NO_UP_REAL_DIR")
    refuse(type(networks) is dict and set(networks) == set(NETWORK_CLASSES), "REAL_NETWORKS_NOT_THE_THREE_CLASSES")
    refuse(networks == NETWORKS, "REAL_NETWORKS_NOT_DNET", [c for c in NETWORK_CLASSES if networks[c] != NETWORKS[c]][:1])
    k9raw = real_k9_inputs(real_k9)
    rt.stamp(owner_deadline, Refused)
    lay = rt.validate_layout(bind.loose_json(layout_path), Refused)
    m = real_plans(plans_dir, go)
    manifest_raw = read_file(Path(plans_dir) / "K9_04_STEP_SET_MANIFEST.json")
    refuse(rt.strict(manifest_raw, kind=Refused) == m, "REAL_K9_BYTES_CHANGED_WHILE_READ")
    constants = rt.strict(read_file(Path(plans_dir) / "plans" / "prove_launch.json"), kind=Refused)["constants"]
    real_files, sources, kill = k9_real_bindings(lot, m, manifest_raw, constants, k9raw, secrets_root, networks, lay)
    plans_abs, go_abs = str(Path(plans_dir)), str(Path(go))
    if lot == "UP":
        spec = build_up(secrets_root, networks, plans=plans_abs, go=go_abs, owner_deadline=owner_deadline)
    else:
        spec = build_down(secrets_root, networks, plans=plans_abs, go=go_abs, lay=lay, owner_deadline=owner_deadline)
    # v3.3f: the REAL files enter SPEC.files from the explicit inputs (the verifier replaces its DRAFT placeholder)
    refuse(spec["files"].get(rt.K9_REAL_VERIFIER) == VERIFIERS_PLACEHOLDER
           and not (set(sources) - {rt.K9_REAL_VERIFIER}) & set(spec["files"]), "REAL_K9_ORIGINAL_PATH_INVALID")
    for rel, key in sources.items():
        spec["files"][rel] = str(Path(real_k9[key[0]] if len(key) == 1 else real_k9["originals"][key[1]]))
    spec = substitute(spec, bind.loose_json(values_path))
    windows = windows_or_refuse(spec)
    prepared = validation_instant(owner_deadline)
    stub = runtime_stub(lay)
    authority_raw, request_raw, authority, q, extra = bind.build_lot(spec, lay, stub, prepared, LOTS, physical=True)
    refuse(rt.sha(extra["k9/K9_04_STEP_SET_REQUEST.json"]) == m["request_sha256"]
           and rt.sha(extra["k9/K9_GO_04.json"]) == m["go_sha256"]
           and all(rt.sha(extra[rel]) == m["steps"][op]["plan_sha256"] for op, rel in spec["k9"]["plans"].items())
           and all(extra.get(rel) == raw for rel, raw in real_files.items()), "REAL_K9_BYTES_CHANGED_WHILE_READ")
    recorded = {r["operation"]: r["row"] for r in json.loads(kill)["rows"]}
    refuse(all(recorded[op] == row for op, row in rt.k9_effect_rows(authority, q["lane"]).items()),
           "REAL_KILL_RECORD_NOT_THE_SPEC_ROWS")
    records = {MANIFEST_RECORD: manifest_raw, KILL_RECORD: kill}
    cross = anchor = None
    if lot == "UP":
        anchor = read_file(Path(plans_dir) / "plans" / "capture_launch.json")
        refuse(rt.sha(anchor) == m["steps"]["capture_launch"]["plan_sha256"], "REAL_K9_BYTES_CHANGED_WHILE_READ")
    else:
        cross = down_matches_up(up_real_dir, layout_path, extra, m, records)
    name = lot + ".SPEC.json"
    bare = copy.deepcopy(spec)
    bare["files"] = {rel: rel for rel in spec["files"]}
    spec_raw = (json.dumps(bare, sort_keys=True, indent=1) + "\n").encode("ascii")
    os.mkdir(str(target), 0o700)
    recheck_created(target)
    written = {rel: write_file(target, rel, raw) for rel, raw in sorted(extra.items())}
    for rel, raw in sorted(records.items()):
        written[rel] = write_file(target, rel, raw)
    if anchor is not None:
        written[UP_CAPTURE_ANCHOR] = write_file(target, UP_CAPTURE_ANCHOR, anchor)
    written[name] = write_file(target, name, spec_raw)
    again = bind.build_lot(bind.loose_json(target / name), lay, stub, prepared, target, physical=True)
    refuse(again[0] == authority_raw and again[1] == request_raw, "REAL_SPEC_REREAD_DIFFERS")
    sums = "".join("%s  %s\n" % (written[k], k) for k in sorted(written)).encode("ascii")
    sums_sha = write_file(target, "SHA256SUMS", sums)
    out = {"status": "REAL_SPEC_WRITTEN_OUTSIDE_THE_FAMILY", "lot": lot, "out_dir": str(target), "spec": name,
           "spec_sha256": written[name], "sha256sums_sha256": sums_sha, "files": len(written),
           "grid": m["grid"]["id"], "grid_slots_sha256": m["grid"]["slots_sha256"], "plans_manifest_request_sha256":
           m["request_sha256"], "go_sha256": m["go_sha256"], "layout_sha256": rt.sha(rt.canonical(lay)),
           "owner_deadline": owner_deadline, "validated_physical": True, "start_windows": windows,
           "slack": slack_table(spec), "networks": dict(networks), "unit_networks": dict(UNIT_NETWORKS),
           "k9_real": real_summary(real_files, sources, k9raw["verifier"]),
           "kill_record": {"file": KILL_RECORD, "sha256": written[KILL_RECORD],
                           "manifest": {"file": MANIFEST_RECORD, "sha256": written[MANIFEST_RECORD]}}}
    if lot == "UP":
        out["capture_launch_anchor"] = {"file": UP_CAPTURE_ANCHOR, "sha256": written[UP_CAPTURE_ANCHOR]}
    else:
        out["up_cross_check"] = cross
    return out


def kill_record_command(plans_dir, go, layout_path, secrets_root, networks):
    """v3.3f `kill-record`: the KILL changed-row record of a REAL plans run, BEFORE any REAL write (the registry Codex
    issues must register its row hashes as effect_sha256). Prints it; writes nothing."""
    refuse(type(networks) is dict and set(networks) == set(NETWORK_CLASSES), "REAL_NETWORKS_NOT_THE_THREE_CLASSES")
    refuse(networks == NETWORKS, "REAL_NETWORKS_NOT_DNET", [c for c in NETWORK_CLASSES if networks[c] != NETWORKS[c]][:1])
    refuse(secrets_root in rt.EPOCH04_SECRETS_ROOTS, "K9_SECRETS_ROOT_NOT_ALLOWED")
    lay = rt.validate_layout(bind.loose_json(layout_path), Refused)
    m = real_plans(plans_dir, go)
    manifest_raw = read_file(Path(plans_dir) / "K9_04_STEP_SET_MANIFEST.json")
    refuse(rt.strict(manifest_raw, kind=Refused) == m, "REAL_K9_BYTES_CHANGED_WHILE_READ")
    raw = kill_record(m, manifest_raw, secrets_root, networks, lay)
    record = json.loads(raw)
    return {"status": "KILL_RECORD_DERIVED_NOTHING_WRITTEN", "sha256": rt.sha(raw), "bytes": len(raw),
            "rows": {r["operation"]: {"row_sha256": r["row_sha256"], "derivation": r["derivation"]}
                     for r in record["rows"]}, "record": record}


def real_dir(out_dir):
    """A written REAL dir, integrity only: (absolute target, SHA256SUMS bytes, {rel: sha256}); SHA256SUMS lists every
    file exactly and every listed byte matches. v3.3 (lots review LOW 6): a relative DIR is made absolute, as `write`
    does, and a DIR that is not a real directory is refused as such."""
    target = Path(os.path.abspath(str(out_dir)))
    refuse(target.is_dir() and not target.is_symlink(), "REAL_SPEC_DIR_NOT_A_DIRECTORY")
    sums = read_file(target / "SHA256SUMS")
    listed = {}
    for line in sums.decode("ascii").splitlines():
        digest, _, rel = line.partition("  ")
        refuse(len(digest) == 64 and rel and rel not in listed, "REAL_DIR_SUMS_INVALID")
        listed[rel] = digest
    present = {p.relative_to(target).as_posix() for p in target.rglob("*") if not p.is_dir()} - {"SHA256SUMS"}
    refuse(set(listed) == present, "REAL_DIR_FILE_SET_MISMATCH")
    refuse(all(rt.sha(read_file(target / rel)) == digest for rel, digest in listed.items()), "REAL_DIR_BYTES_MISMATCH")
    return target, sums, listed


def check_real(out_dir, layout_path):
    """Re-checks a written REAL dir; writes nothing."""
    target, sums, listed = real_dir(out_dir)
    names = [n for n in listed if n.endswith(".SPEC.json")]
    refuse(len(names) == 1 and names[0] in ("UP.SPEC.json", "DOWN.SPEC.json"), "REAL_DIR_SPEC_INVALID")
    spec = bind.loose_json(target / names[0])
    refuse(spec.get("lot") + ".SPEC.json" == names[0] and not placeholders(spec), "REAL_DIR_SPEC_INVALID")
    request_raw = read_file(target / K9_REQUEST)
    request = rt.strict(request_raw, kind=Refused)
    grid = request.get("grid")
    refuse(type(grid) is dict and grid.get("id") in ELECTED_GRIDS and grid == generator().grid_block(grid["id"]),
           "REAL_PLANS_GRID_NOT_ELECTED")
    if spec["lot"] == "UP":
        # v3.3 (F1): the UP dir carries the capture_launch plan of ITS plans run, bound to its request and GO
        refuse(UP_CAPTURE_ANCHOR in listed, "REAL_UP_CAPTURE_ANCHOR_INVALID")
        anchor = rt.strict(read_file(target / UP_CAPTURE_ANCHOR), kind=Refused)
        refuse(anchor.get("k9_operation") == "capture_launch" and anchor.get("request_sha256") == rt.sha(request_raw)
               and anchor.get("go_sha256") == rt.sha(read_file(target / K9_GO))
               and type(anchor.get("step_row")) is dict and anchor["step_row"].get("grid") == grid,
               "REAL_UP_CAPTURE_ANCHOR_INVALID")
    windows = windows_or_refuse(spec)
    lay = rt.validate_layout(bind.loose_json(layout_path), Refused)
    real = check_real_k9(target, listed, spec, request_raw, lay)
    bind.build_lot(spec, lay, runtime_stub(lay), validation_instant(spec["owner_deadline"]), target, physical=True)
    return {"status": "REAL_SPEC_DIR_VALID", "lot": spec["lot"], "spec_sha256": listed[names[0]],
            "sha256sums_sha256": rt.sha(sums), "files": len(listed), "grid": grid["id"],
            "layout_sha256": rt.sha(rt.canonical(lay)), "start_windows": windows, "k9_real": real,
            "kill_record": {"file": KILL_RECORD, "sha256": listed[KILL_RECORD]}}


def check_real_k9(target, listed, spec, request_raw, lay):
    """v3.3f, `validate`: the dir's REAL K9 files and records re-bound exactly as `write` bound them (the KILL record
    re-derived byte for byte from the recorded manifest, this layout and the spec's secrets root / networks)."""
    k9 = spec.get("k9") or {}
    refuse(k9.get("networks") == NETWORKS, "REAL_NETWORKS_NOT_DNET")
    needed = (MANIFEST_RECORD, KILL_RECORD, K9_GO, RUNNER_REL) + rt.K9_REAL_FIXED_FILES
    refuse(all(rel in listed for rel in needed) and all(spec["files"].get(rel) == rel for rel in rt.K9_REAL_FIXED_FILES),
           "REAL_DIR_K9_REAL_FILES_ABSENT")
    manifest_raw = read_file(target / MANIFEST_RECORD)
    m = canonical_doc(manifest_raw, "REAL_DIR_MANIFEST_RECORD_NOT_THIS_RUN")
    refuse(m.get("request_sha256") == rt.sha(request_raw) and m.get("go_sha256") == rt.sha(read_file(target / K9_GO))
           and type(m.get("steps")) is dict and set(k9["plans"]) <= set(m["steps"])
           and all(m["steps"][op]["plan_sha256"] == listed.get(rel) for op, rel in k9["plans"].items())
           and m.get("runner", {}).get("sha256") == listed[RUNNER_REL]
           and m.get("grid") == rt.strict(request_raw, kind=Refused).get("grid"), "REAL_DIR_MANIFEST_RECORD_NOT_THIS_RUN")
    constants = rt.strict(read_file(target / k9["plans"][sorted(k9["plans"])[0]]), kind=Refused)["constants"]
    raw = {key: read_file(target / rel) for key, rel in (("verifier", rt.K9_REAL_VERIFIER), ("policy", rt.K9_REAL_POLICY),
                                                         ("review", rt.K9_REAL_REVIEW),
                                                         ("publication", rt.K9_REAL_PUBLICATION))}
    declared = canonical_doc(raw["policy"], "REAL_K9_POLICY_INVALID").get("originals")
    refuse(type(declared) is dict and all(type(r) is dict and r.get("file") in listed for r in declared.values()),
           "REAL_DIR_K9_REAL_FILES_ABSENT")
    raw["originals"] = {name: read_file(target / r["file"]) for name, r in declared.items()}
    files, sources, kill = k9_real_bindings(spec["lot"], m, manifest_raw, constants, raw, k9["secrets_root"],
                                            k9["networks"], lay)
    refuse(all(spec["files"].get(rel) == rel for rel in files), "REAL_DIR_K9_REAL_FILES_ABSENT")
    refuse(read_file(target / KILL_RECORD) == kill, "REAL_KILL_RECORD_NOT_THE_DERIVED_ONE")
    return real_summary(files, sources, raw["verifier"])


# v3.3f (F1 extended): the REAL K9 files and records the DOWN must share with the UP (the registries: all but `lot`)
F1_SHARED = (rt.K9_REAL_VERIFIER, rt.K9_REAL_REVIEW, rt.K9_REAL_PUBLICATION)


def down_matches_up(up_real_dir, layout_path, extra, m, records):
    """v3.3 (lots review F1, MEDIUM): the REAL DOWN uses byte-identical K9 request, GO, runner and capture_launch plan
    bytes as the UP REAL spec, and the same grid id. The comparisons come first (each mismatch has its own code), then
    the whole UP dir is re-validated (check_real). Writes nothing. v3.3f: also byte-identical verifier, review,
    publication, originals and records (manifest, KILL changed rows), and the two registries equal except `lot`."""
    try:
        up_dir, _, listed = real_dir(up_real_dir)
    except rt.Hold as error:
        raise Refused("REAL_DOWN_UP_DIR_INVALID", rt.safe_code(error)) from None
    shared = (K9_REQUEST, K9_GO, RUNNER_REL, UP_CAPTURE_ANCHOR, rt.K9_REAL_POLICY, MANIFEST_RECORD, KILL_RECORD) + F1_SHARED
    refuse("UP.SPEC.json" in listed and all(rel in listed for rel in shared), "REAL_DOWN_UP_DIR_NOT_AN_UP_REAL_DIR")
    up = {rel: read_file(up_dir / rel) for rel in shared}
    up_grid = rt.strict(up[K9_REQUEST], kind=Refused).get("grid")
    up_grid_id = up_grid.get("id") if type(up_grid) is dict else None
    refuse(up_grid_id == m["grid"]["id"], "REAL_DOWN_GRID_NOT_THE_UP_ONE", [up_grid_id, m["grid"]["id"]])
    refuse(up[K9_REQUEST] == extra[K9_REQUEST], "REAL_DOWN_K9_REQUEST_NOT_THE_UP_ONE")
    refuse(up[K9_GO] == extra[K9_GO], "REAL_DOWN_K9_GO_NOT_THE_UP_ONE")
    refuse(up[RUNNER_REL] == extra[RUNNER_REL], "REAL_DOWN_RUNNER_NOT_THE_UP_ONE")
    refuse(up[UP_CAPTURE_ANCHOR] == extra[DOWN_CAPTURE_PLAN], "REAL_DOWN_CAPTURE_PLAN_NOT_THE_UP_ONE")
    for rel, code in zip(F1_SHARED, ("REAL_DOWN_K9_VERIFIER_NOT_THE_UP_ONE", "REAL_DOWN_K9_REVIEW_NOT_THE_UP_ONE",
                                     "REAL_DOWN_K9_PUBLICATION_NOT_THE_UP_ONE")):
        refuse(up[rel] == extra[rel], code)
    up_policy = canonical_doc(up[rt.K9_REAL_POLICY], "REAL_DOWN_UP_DIR_INVALID")
    down_policy = json.loads(extra[rt.K9_REAL_POLICY])
    refuse(up_policy.get("lot") == "UP" and down_policy["lot"] == "DOWN"
           and dict(up_policy, lot=None) == dict(down_policy, lot=None), "REAL_DOWN_K9_POLICY_NOT_THE_UP_ONE_BUT_LOT")
    for r in down_policy["originals"].values():
        refuse(r["file"] in listed and read_file(up_dir / r["file"]) == extra[r["file"]],
               "REAL_DOWN_K9_ORIGINALS_NOT_THE_UP_ONES")
    refuse(up[MANIFEST_RECORD] == records[MANIFEST_RECORD] and up[KILL_RECORD] == records[KILL_RECORD],
           "REAL_DOWN_KILL_RECORD_NOT_THE_UP_ONE")
    try:
        checked = check_real(str(up_dir), layout_path)
    except rt.Hold as error:
        raise Refused("REAL_DOWN_UP_DIR_INVALID", rt.safe_code(error)) from None
    refuse(checked["lot"] == "UP", "REAL_DOWN_UP_DIR_NOT_AN_UP_REAL_DIR")
    return {"up_real_dir": str(up_dir), "up_spec_sha256": checked["spec_sha256"],
            "up_sha256sums_sha256": checked["sha256sums_sha256"], "grid": up_grid_id,
            "k9_request_sha256": rt.sha(up[K9_REQUEST]), "go_sha256": rt.sha(up[K9_GO]),
            "runner_sha256": rt.sha(up[RUNNER_REL]), "capture_launch_plan_sha256": rt.sha(up[UP_CAPTURE_ANCHOR]),
            "k9_verifier_sha256": rt.sha(up[rt.K9_REAL_VERIFIER]), "k9_review_sha256": rt.sha(up[rt.K9_REAL_REVIEW]),
            "k9_publication_sha256": rt.sha(up[rt.K9_REAL_PUBLICATION]),
            "up_k9_policy_sha256": rt.sha(up[rt.K9_REAL_POLICY]),
            "originals_sha256": {n: r["sha256"] for n, r in sorted(down_policy["originals"].items())},
            "kill_record_sha256": rt.sha(up[KILL_RECORD]), "manifest_record_sha256": rt.sha(up[MANIFEST_RECORD]),
            "byte_identical": True}


UP_COMMENT = ["L12-HOST v3.1 UP lot SPEC, REAL values; build_specs.py builds it from the gen_k9_plans04 output.",
              "DRAFT until Saturday: act B 04 and the K9 04 GO (plan bytes and hashes change; regenerate the plans with",
              "the real files and rebuild), ext/k9_verifiers04.py (Codex-reviewed REAL verifiers), D-NET network names,",
              "secrets_root (REQUEST parameter, decision pending Codex). Not signed data until the owner's Assino.",
              "v3.1: every LAUNCH row's inner KILL is budget - 65 s (generator: budget - 35 s) so the effect may start up",
              "to 45 s after its instant (30 s beyond the 15 s gate allowance); Codex ruling on the runner's DEADLINE",
              "receipt window (55 s -> 25 s + lateness) requested (CONTRACT 9.3)."]
DOWN_COMMENT = ["L12-HOST v3.1 DOWN lot SPEC DRAFT (B3: no PRE_OPEN reader start; one late session start claim at",
                "10:29:02 BRT; K9 capture as an EXTENDED step; v3.1 early read-only ready_check R0 at 09:30 BRT).",
                "Every @P_...@ is unknown today. Supervisor state root /var/lib/c3po-bar/supervisor-e04 and config",
                "/etc/c3po-reader-e04/supervisor are PROPOSALS for INSTALL_TREE04. J budget 300 s and the J2/J3 instants",
                "are drafts. Not signed data.",
                "Lots patch v3.4 (L-02): PO post 06:01:30 BRT (09:01:30Z, window [09:01:00Z, 09:03:30Z)), 30 s after E6;",
                "[at, at + 60 s] + 45 s ends 06:03:15, before the engine's first forbidden second 06:03:40 (margin 130 s)."]


def main(argv):
    if argv == ["write"]:
        out = {"UP.SPEC.json": write(LOTS / "UP.SPEC.json", build_up(), UP_COMMENT),
               "DOWN.SPEC.DRAFT.json": write(LOTS / "DOWN.SPEC.DRAFT.json", build_down(), DOWN_COMMENT)}
    elif argv == ["validate"]:
        out = {"UP": validate_up(), "DOWN": validate_down()}
    else:
        p = argparse.ArgumentParser(prog="build_specs.py", description=__doc__,
                                    formatter_class=argparse.RawDescriptionHelpFormatter)
        p.add_argument("command", choices=("write", "validate", "kill-record"))
        p.add_argument("--out-dir")
        p.add_argument("--layout", required=True)
        for flag in ("--lot", "--plans-dir", "--go", "--secrets-root", "--owner-deadline", "--values", "--up-real-dir",
                     "--k9-verifier", "--k9-verifier-sha256", "--k9-policy", "--k9-review", "--k9-publication"):
            p.add_argument(flag)
        p.add_argument("--network", action="append", default=[])
        p.add_argument("--k9-original", action="append", default=[])          # v3.3f: NAME=PATH, one per original
        a = p.parse_args(argv)
        k9_flags = {"verifier": a.k9_verifier, "verifier_sha256": a.k9_verifier_sha256, "policy": a.k9_policy,
                    "review": a.k9_review, "publication": a.k9_publication}
        try:
            pairs = [n.split("=", 1) for n in a.network]
            refuse(all(len(x) == 2 for x in pairs) and len(pairs) == len(dict(pairs)), "REAL_NETWORKS_NOT_THE_THREE_CLASSES")
            if a.command == "validate":
                refuse(a.out_dir and not any((a.lot, a.plans_dir, a.go, a.secrets_root, a.owner_deadline, a.values,
                                              a.network, a.up_real_dir, a.k9_original) + tuple(k9_flags.values())),
                       "ARGUMENTS_INVALID")
                out = check_real(os.path.abspath(a.out_dir), a.layout)          # v3.3 (LOW 6): absolute, as write
            elif a.command == "kill-record":
                refuse(all((a.plans_dir, a.go, a.secrets_root)) and not any(
                    (a.out_dir, a.lot, a.owner_deadline, a.values, a.up_real_dir, a.k9_original)
                    + tuple(k9_flags.values())), "ARGUMENTS_INVALID")
                out = kill_record_command(os.path.abspath(a.plans_dir), os.path.abspath(a.go), a.layout,
                                          a.secrets_root, dict(pairs))
            else:
                refuse(a.out_dir and all((a.lot, a.plans_dir, a.go, a.secrets_root, a.owner_deadline, a.values)),
                       "ARGUMENTS_INVALID")
                originals = [x.split("=", 1) for x in a.k9_original]
                refuse(all(len(x) == 2 and x[0] and x[1] for x in originals) and len(originals) == len(dict(originals)),
                       "REAL_K9_ORIGINAL_FLAG_INVALID")
                real_k9 = {k: (v if k == "verifier_sha256" else os.path.abspath(v))
                           for k, v in k9_flags.items() if v is not None}
                if originals:
                    real_k9["originals"] = {name: os.path.abspath(path) for name, path in originals}
                out = write_real(a.lot, a.out_dir, plans_dir=os.path.abspath(a.plans_dir), go=os.path.abspath(a.go),
                                 layout_path=a.layout, secrets_root=a.secrets_root, networks=dict(pairs),
                                 owner_deadline=a.owner_deadline, values_path=a.values,
                                 up_real_dir=os.path.abspath(a.up_real_dir) if a.up_real_dir else None,
                                 real_k9=real_k9)
        except (ValueError, OSError, KeyError, TypeError, AttributeError) as error:
            print(json.dumps({"status": "REFUSED", "command": a.command, "code": rt.safe_code(error)
                              if not isinstance(error, OSError) else "REAL_IO_" + type(error).__name__.upper(),
                              "detail": getattr(error, "detail", None)}, sort_keys=True))
            return 2
    print(json.dumps(out, sort_keys=True, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
