"""L12-HOST v3 lot SPECs of epoch 04 (Fable, Mac, offline): UP.SPEC.json filled with REAL values and the DOWN draft.

    python3 -I -B lots/build_specs.py write       -> lots/UP.SPEC.json, lots/DOWN.SPEC.DRAFT.json (refuses to overwrite)
    python3 -I -B lots/build_specs.py validate    -> both specs through bind_l12host.build_lot in PHYSICAL mode (every
                                                     v3 rule and epoch-04 guard) after replacing ONLY the declared
                                                     placeholders with synthetic fill-ins; prints the summaries.

UP (Saturday 10/10): the real image sha256:bf37cec9..., revision de96aee9..., package 43db2b96..., runner04 e9be2b30...
(full-hash name), the 11 UP plans generated by Codex's gen_k9_plans04 2b08ee13 with the REAL release 5fd6eadb... and
policy 6757e791... (lots/up_plans_DRAFT_actB_GO_pending, generated from lots/up_inputs). The rows are the generator's
manifest rows converted to the v3 CONTAINER shape (network per class, env files and emitter mount from the secrets
root REQUEST parameter). Placeholders that stay until Saturday / Codex:
    act B 04 and the K9 04 GO     -> the plan bytes (and so every plan hash) are DRAFT: regenerate with the real files
    ext/k9_verifiers04.py          -> the Codex-reviewed K9 approval/original/step verifiers (REAL, pinned)
    networks (D-NET)               -> PROVIDER bridge (K9W epoch-03 constant), DATABASE* c3po_default (compose default)
    secrets_root                   -> REQUEST parameter; default = the generator's epoch-03 root (Codex root closure:
                                      CONDITIONAL_READONLY_REUSE_MATERIAL_ONLY); INSTALL_TREE04 rev 2 also creates
                                      the epoch-04 copies under /var/lib/c3po/r2d2-v2-k9-20261012/secrets.
DOWN (Sunday 11/10, B3): e6, J (J1/J2/J3 of ONE attempt), post in the core; the late session start and the K9 capture as
EXTENDED steps; gate (bounded readback r1), capacity and READY sections. Every unknown is an @P_...@ placeholder.

Lots patch v3.4 (L-06, L-02, L-01). The in-family `write` and `validate` above are unchanged, except that the DOWN draft's
PO now starts at 06:01:30 BRT (09:01:30Z; L-02) and `validate` also reports every slot's start-window margin. The REAL
specs are written OUTSIDE the sealed family, so they never change its seal:

    python3 -I -B lots/build_specs.py write --out-dir DIR --lot UP|DOWN --plans-dir P --go F --layout L
            --secrets-root S --network PROVIDER=N --network DATABASE=N --network DATABASE_AND_PROVIDER=N
            --owner-deadline Z --values V.json
        DIR (created 0700; must not exist; never inside the family root or its sealed delivery, symlinks and case
        resolved by device/inode) receives <LOT>.SPEC.json (the bare spec `bind_l12host.py lot --spec` reads), every
        file the spec names copied byte for byte under its signed relative name, and SHA256SUMS; each file O_EXCL 0600.
        P is a gen_k9_plans04 output of an ELECTED grid (C/D; never DRAFT3_REJECTED, never synthetic), byte-equal to its
        manifest, with the family's runner; F is the manifest's GO (never the draft placeholder); V maps EVERY @P_...@
        placeholder of the lot to its real value (a placeholder that names a file maps to that file's absolute path);
        none may remain and no other key is accepted. Every slot's [at, at + 60 s] + 45 s must be allowed by the
        engine's start-minute rule. The spec passes bind_l12host.build_lot in PHYSICAL mode before the first write and
        again re-read from DIR. Nothing inside the family is written.
    python3 -I -B lots/build_specs.py validate --out-dir DIR --layout L
        Re-checks a written REAL dir (SHA256SUMS exact, no placeholder, elected grid, start windows, physical build_lot);
        writes nothing.

v3.3 (lots patch review: GO with condition F1, and LOW 6):
    F1  `write --lot DOWN` also needs `--up-real-dir U` (the written REAL UP dir; refused for `--lot UP`) and refuses
        before any write unless the DOWN's K9 request, GO, runner and capture_launch plan are byte-identical to the
        UP's and its grid id is the UP's (REAL_DOWN_GRID_NOT_THE_UP_ONE, REAL_DOWN_K9_REQUEST_NOT_THE_UP_ONE,
        REAL_DOWN_K9_GO_NOT_THE_UP_ONE, REAL_DOWN_RUNNER_NOT_THE_UP_ONE, REAL_DOWN_CAPTURE_PLAN_NOT_THE_UP_ONE), then
        re-validates U whole (REAL_DOWN_UP_DIR_INVALID). For that check the REAL UP dir also holds
        cross_lot/capture_launch.json, the capture_launch plan of ITS plans run (listed in its SHA256SUMS, bound by
        `validate` to its request and GO, not named by the UP spec, so `bind_l12host.py lot` never reads it).
    LOW 6  `validate --out-dir` takes a relative DIR as `write` does (made absolute); a DIR that is not a directory is
        REAL_SPEC_DIR_NOT_A_DIRECTORY.
"""
import argparse
import copy
from datetime import timedelta
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile
import types

LOTS = Path(__file__).resolve().parent
FAMILY = LOTS.parent
sys.path.insert(0, str(FAMILY / "vendor"))
sys.path.insert(0, str(FAMILY))
import l12host_runtime as rt      # noqa: E402
import l12host_effect as fx       # noqa: E402
import bind_l12host as bind       # noqa: E402

PLANS = "up_plans_DRAFT_actB_GO_pending"
DRAFT_GO = "up_inputs/K9_GO_04.PLACEHOLDER.txt"
DRAFT_ACT_B = "up_inputs/ACT_B_04.PLACEHOLDER.txt"
RUNNER = "k9tools/k9_runner04.py"
GENERATOR = "k9tools/gen_k9_plans04.py"
GEN_SECRETS_ROOT = "/var/lib/c3po/r2d2-v2-k9-20261005/secrets"
NETWORKS = {"PROVIDER": "bridge", "DATABASE": "c3po_default", "DATABASE_AND_PROVIDER": "c3po_default"}
D1 = "09de76e5a2ee54fdcdfa477b0f8df101fcda761b7f416e4308e29c0235e51c2a"
ORDER = "70cb947fc5276949ca3f08d53cfaf79873463a83f36a64859056d7616fcdf9d3"
IMAGE = "sha256:bf37cec9f4f93e129543235a567a2de5daad0c8116086e2b176069e497defba3"
REVISION = "de96aee90a26e9587663ba7a1f6e55a592afcd20"
PACKAGE = "43db2b969fe113594fafe4a9e0cabec1f80ada9f8ab9ee5852677d65e2ec716a"
RELEASE = "5fd6eadbf8c1c899598e23c52e98599fe9cc990bd33a182cc363d2c05c5784ab"
POLICY = "6757e79112770f948b73770f6b6b87f209930afe8cd00f9517d378055e0d2d92"
VERIFIERS_PLACEHOLDER = "@P_CODEX_REVIEWED_K9_VERIFIERS04_PY@"
CORE = (("prove", "prove_launch", []), ("collect", "collect_launch", ["prove"]),
        ("commit_result", "commit_launch", ["collect"]), ("publish_launch", "publish_launch", ["commit_result"]))
J4_PROGRAMS = {"hot_runtime": "55e2cc2c97c73d0b7ae9ad8289b9cf7ff28dfb26321690b5ea40cb21438921bc",
               "hot_worker": "0edb64f45b8a4e31e64aa274e778566106e3549d7e8fe2ab8d746dd1b751d8fa",
               "hot_watchdog": "12ce74398c8bb5d0a48af8d528dc40be8703860b7cd47223328cdb9e6c073def",
               "finite_batch": "809a816d4179ee889531bfc2d270e193508f0d1a31d7a30a48159151f80dbeec",
               "folder_veto": "8d63f75cad847da5d4f5ede7dedba24b64ea296d86bad67d16fb5f8e02271b18",
               "veto_emitter": "b3ea98c4e35d749946f95b32b7dbf8e726779c70fa9f5e5001572a3f24045817",
               "config_finalizer": "45dce62d7f8e17cb3d93bfefa480352778234cc9ee88c632ad9a5268b732a30d",
               "consumer_codec": "57933d7cf4d79b62ab1c7b291b8c460a743864c78d5ad5a3111c9b2c0b76f2b6",
               "j_slot": "d4c029cabf895276e81dec38f38b387be9c85f03d4e26926846d3c8c8505db04",
               "authority_bridge": "@P_J4_AUTHORITY_BRIDGE_REAL_SHA256@"}
# L-02 / L-01 (Codex P4 ruling): a slot may start up to at + LATE_SECONDS and a K9 row reaches its effect up to 45 s
# after its instant; [at, at + 60 s] + 45 s must lie wholly before the engine's next forbidden second.
EFFECT_LEAD_SECONDS = 45
START_WINDOW_SECONDS = rt.LATE_SECONDS + EFFECT_LEAD_SECONDS
ELECTED_GRIDS = ("C", "D")
NETWORK_CLASSES = ("PROVIDER", "DATABASE", "DATABASE_AND_PROVIDER")


class Refused(rt.Hold):
    """A refusal of the REAL writer; `detail` names the offending item (never a secret)."""

    def __init__(self, code, detail=None):
        super().__init__(code)
        self.detail = detail


def refuse(ok, code, detail=None):
    if not ok:
        raise Refused(code, detail)


def z(text):
    return text.replace("+00:00", "Z")


def at_minus(text, seconds):
    return rt.iso(rt.stamp(z(text)) - timedelta(seconds=seconds))


def at_plus(text, seconds):
    return rt.iso(rt.stamp(z(text)) + timedelta(seconds=seconds))


def manifest(plans=PLANS):
    """The generator manifest of a plans directory (relative to lots/, or absolute for a REAL one)."""
    return json.loads((LOTS / plans / "K9_04_STEP_SET_MANIFEST.json").read_bytes())


DOCKER_MARGIN = 20                        # l12host_effect.DOCKER_MARGIN_SECONDS
SLACK_KILL = DOCKER_MARGIN + rt.GATE_ALLOWANCE_SECONDS + rt.EFFECT_LATENESS_SLACK_SECONDS     # 65 s


def kill_with_slack(step):
    """v3.1 (finding 8): the inner KILL of an UP row leaves >= 30 s of slack beyond (effect floor + gate allowance):
    KILL = min(generator KILL, budget - 20 - 15 - 30). For a LAUNCH step the generator's KILL is budget - 35 (the
    runner stops itself at run_not_after - 60 = start + budget - 90 and has < 55 s to write its DEADLINE receipt);
    with KILL = budget - 65 that window is 25 s + the effect lateness (Codex ruling requested; CONTRACT 9.3)."""
    return min(step["l12_effect"]["docker"]["timeout_seconds"], step["budget_seconds"] - SLACK_KILL)


def convert(step, secrets_root, networks, *, slack=True):
    """The generator's K9STEP row (v1 shape) -> the v3 CONTAINER row: network per class, env files and the emitter
    mount re-rooted at the secrets root parameter, receipt FILE, no `mode` (ATTACHED is the only mode). v3.1: UP rows
    get the slack KILL (kill_with_slack); the DOWN capture keeps the generator's KILL (its shell ceiling 750 s is above
    the plan budget 690 s and already leaves 30 s)."""
    e = step["l12_effect"]
    d = e["docker"]
    swap = lambda p: secrets_root + p[len(GEN_SECRETS_ROOT):] if p.startswith(GEN_SECRETS_ROOT + "/") else p
    cls = step["network_class"]
    return {"kind": "CONTAINER", "docker": {
        "name": d["name"], "labels": d["labels"], "network": "none" if cls == "NONE" else networks[cls],
        "env_files": [swap(p) for p in d["env_files"]], "env": d["env"],
        "mounts": [dict(m, source=swap(m["source"])) for m in d["mounts"]], "tmpfs": d["tmpfs"], "workdir": d["workdir"],
        "image_id": d["image_id"], "command": d["command"],
        "timeout_seconds": kill_with_slack(step) if slack else d["timeout_seconds"]},
        "receipt": {"source": "FILE", "path": e["receipt"]["path"]}}


def slack_table(spec):
    """budget floor vs effect lateness of every K9 row of a spec (CONTRACT 9.3)."""
    rows = []
    for t in spec["tasks"]:
        d = t["effect"].get("docker")
        if d:
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": t["operation"], "budget": t["budget_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": t["budget_seconds"] - floor,
                         "slack_beyond_allowance": t["budget_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS})
    for s in (spec["extended"] or {}).get("steps", []):
        d = (s["effect"] or {}).get("docker")
        if d:
            extra = 2 * rt.GATE_ALLOWANCE_SECONDS if s["step"] == "capture_launch" else 0
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": s["step"], "budget": s["ceiling_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": s["ceiling_seconds"] - floor - extra,
                         "slack_beyond_allowance": s["ceiling_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS - extra})
    return rows


def start_margin(at, horizon=6 * 3600):
    """Seconds from the instant `at` to the first second the ENGINE's start-minute rule refuses."""
    for k in range(horizon):
        if fx.start_minute_violation(at + timedelta(seconds=k)) is not None:
            return k
    return horizon


def start_windows(spec):
    """Every slot of a spec, by instant: its margin to the engine's next forbidden second and whether the whole
    [at, at + 60 s] + 45 s is allowed (margin > 105 s)."""
    rows = []
    for owner in list(spec["tasks"]) + list((spec["extended"] or {}).get("steps", [])):
        for s in owner["slots"]:
            at = rt.stamp(s["at"], rt.Hold)
            margin = start_margin(at)
            rows.append({"slot": s["slot"], "target": owner.get("operation") or owner.get("step"), "at": s["at"],
                         "brt": at.astimezone(rt.BRT).strftime("%a %d/%m %H:%M:%S"), "margin_seconds": margin,
                         "needed_seconds": START_WINDOW_SECONDS + 1, "ok": margin > START_WINDOW_SECONDS})
    return sorted(rows, key=lambda r: r["at"])


def k9_decoder(op, row, nb, na, mode="REAL"):
    return {"kind": "K9_STEP_V1", "mode": mode, "runner_source": "ext/k9_runner04.py", "step_plan": "k9/%s.json" % op,
            "k9_request": "k9/K9_04_STEP_SET_REQUEST.json", "k9_go": "k9/K9_GO_04.json",
            "provenance_binding_sha256": rt.sha(rt.canonical(row)), "phase_not_before": nb, "phase_not_after": na,
            "verifiers": {"approval": "k9_approval", "original": "k9_original"}}


def k9_files(ops, plans=PLANS, go=DRAFT_GO):
    files = {"ext/k9_runner04.py": RUNNER,
             "k9/K9_04_STEP_SET_REQUEST.json": plans + "/K9_04_STEP_SET_REQUEST.json",
             "k9/K9_GO_04.json": go,
             "ext/k9_verifiers04.py": VERIFIERS_PLACEHOLDER}
    for op in ops:
        files["k9/%s.json" % op] = plans + "/plans/%s.json" % op
    return files


def k9_section(ops, secrets_root, networks):
    return {"runner_source": "ext/k9_runner04.py", "request": "k9/K9_04_STEP_SET_REQUEST.json", "go": "k9/K9_GO_04.json",
            "plans": {op: "k9/%s.json" % op for op in ops}, "networks": dict(networks), "secrets_root": secrets_root}


K9_EXTERNAL = {"k9_approval": {"file": "ext/k9_verifiers04.py", "identity": "verify_approval"},
               "k9_original": {"file": "ext/k9_verifiers04.py", "identity": "verify_original"},
               "k9_step": {"file": "ext/k9_verifiers04.py", "identity": "verify_step"}}


# ------------------------------------------------------------------ UP
def build_up(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS, *, plans=PLANS, go=DRAFT_GO,
             owner_deadline="2026-10-10T13:20:00Z"):
    m = manifest(plans)
    steps = m["steps"]
    tasks, ops = [], []
    for i, (core, op, requires) in enumerate(CORE):
        s = steps[op]
        start = z(s["starts_at_utc"])
        nb, na = at_minus(start, 30), at_plus(start, s["budget_seconds"])
        row = convert(s, secrets_root, networks)
        tasks.append({"operation": core, "not_before": nb, "not_after": na, "budget_seconds": s["budget_seconds"],
                      "requires": requires, "slots": [{"slot": "P%d" % (i + 1), "at": start}], "effect": row,
                      "decoder": k9_decoder(op, row, nb, na), "image_go_sha256": None, "image_proposal_sha256": None})
        ops.append(op)
    ext = []
    for j, (name, (kind, op, requires)) in enumerate(rt.EXTENDED_TABLE["UPSTREAM_P"].items()):
        s = steps[op]
        start = z(s["starts_at_utc"])
        ext.append({"step": name, "not_before": at_minus(start, 30), "not_after": at_plus(start, s["budget_seconds"]),
                    "ceiling_seconds": s["budget_seconds"], "requires": [list(r) for r in requires],
                    "effect": convert(s, secrets_root, networks), "decoder": {"kind": "K9_EXT_STEP_V3", "verifier": "k9_step"},
                    "pre_effect": None, "hold_until": None, "slots": [{"slot": "X%d" % (j + 1), "at": start}]})
        ops.append(op)
    return {"schema": bind.SPEC_SCHEMA, "lot": "UP", "lane": "UPSTREAM_P", "mode": "REAL",
            "owner_deadline": owner_deadline, "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {}, "imports": {}, "files": k9_files(ops, plans, go), "external": dict(K9_EXTERNAL),
            "k9": k9_section(ops, secrets_root, networks), "tasks": tasks, "extended": {"steps": ext},
            "bootstrap": None, "gate": None, "capacity": None, "ready": None, "j4": None}


# ------------------------------------------------------------------ DOWN (draft, B3)
def layout():
    return bind.loose_json(LOTS / "layout.e04.DRAFT.json")


# L-02 (lots patch v3.4): PO starts at 06:01:30 BRT, 30 s after E6 (06:01:00) and long before J1 (07:38:00). Its whole
# [at, at + 60 s] + 45 s ends 06:03:15, 25 s before the engine's first forbidden second 06:03:40 (margin 130 s; the
# former 06:03:00 had 40 s). Window [at - 30 s, at + 120 s), budget 60 s: the shape of the former slot.
PO_AT, PO_NOT_BEFORE, PO_NOT_AFTER = "2026-10-12T09:01:30Z", "2026-10-12T09:01:00Z", "2026-10-12T09:03:30Z"


def build_down(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS, *, plans=PLANS, go=DRAFT_GO, lay=None,
               owner_deadline="2026-10-12T00:44:00Z"):
    m = manifest(plans)
    lay = layout() if lay is None else lay
    docker = lay["binaries"]["docker"]
    reader, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-reader.service"), {
        "@HOST_DATA_ROOT@": "/mnt/day-d-data", "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT,
        "@HOST_CAPACITY_ROOT@": rt.EPOCH04_CAPACITY_ROOT, "@HOST_CONFIG_DIR@": rt.EPOCH04_READER_CONFIG,
        "@IMAGE_ID@": IMAGE, "@NETWORK@": networks["DATABASE"], "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.READER_NAME, "SESSION_READER", lay, [("c3po-reader", rt.READER_NAME)])
    sup_cfg = rt.EPOCH04_READER_CONFIG + "/supervisor"
    supervisor, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-massive.service"), {
        "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT, "@HOST_STATE_ROOT@": rt.EPOCH04_SUPERVISOR_STATE,
        "@HOST_CONFIG_DIR@": sup_cfg, "@IMAGE_ID@": IMAGE, "@NETWORK@": networks["DATABASE"],
        "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.SUPERVISOR_NAME, "SUPERVISOR", lay,
        [("c3po-massive", rt.SUPERVISOR_NAME), ("DOCKER_CONFIG=" + sup_cfg + "/docker-cli", "DOCKER_CONFIG=" + lay["docker_config"])])
    cap = m["steps"]["capture_launch"]
    cap_start = z(cap["starts_at_utc"])
    cap_row = convert(cap, secrets_root, networks, slack=False)
    cap_nb, cap_na = at_minus(cap_start, 30), at_plus(cap_start, 750)
    task = lambda op, slots, req, eff, dec, nb, na, budget: {
        "operation": op, "not_before": nb, "not_after": na, "budget_seconds": budget, "requires": req,
        "slots": slots, "effect": eff, "decoder": dec, "image_go_sha256": None, "image_proposal_sha256": None}
    j_argv = ["--registry-record-base64", rt.J4_REGISTRY_TOKEN, "--mode", "REAL"]
    tasks = [
        task("e6", [{"slot": "E6", "at": "2026-10-12T09:01:00Z"}], ["commit_result", "publish_launch"],
             {"kind": "READBACK", "files": [{"path": "@P_E6_DOCUMENT_PATH@", "sha256": "@P_E6_DOCUMENT_SHA256@",
                                             "mode": 256, "uid": 0}]},
             {"kind": "READBACK_V3"}, "2026-10-12T09:00:30Z", "2026-10-12T09:03:00Z", 60),
        task("admission_manifest", [{"slot": "J1", "at": "2026-10-12T10:38:00Z"}, {"slot": "J2", "at": "2026-10-12T10:41:00Z"},
                                    {"slot": "J3", "at": "2026-10-12T10:44:00Z"}], ["e6"],
             {"kind": "HOST_PROGRAM", "source": "ext/j4_hot_worker.py", "argv": j_argv},
             {"kind": "HOT_J_V1", "verifier": "j4_codec"}, "2026-10-12T10:37:30Z", "2026-10-12T10:50:00Z", 300),
        task("post", [{"slot": "PO", "at": PO_AT}], ["publish_launch"],
             {"kind": "CHAIN_READBACK", "source_lot": "UP", "source_request_sha256": "@P_UP_REQUEST_SHA256@",
              "source_bound_sha256": "@P_UP_BOUND_SHA256@", "steps": list(rt.EXTENDED_TABLE["UPSTREAM_P"])},
             {"kind": "CHAIN_READBACK_V3"}, PO_NOT_BEFORE, PO_NOT_AFTER, 60)]
    steps = [
        # v3.1 (finding 2): the early read-only absence check of the ready file, 09:30 BRT (a person has ~1 h to clear
        # a leftover before the 10:29:02 BRT session start, which re-checks absence itself before the supervisor).
        {"step": "ready_check", "not_before": "2026-10-12T12:29:30Z", "not_after": "2026-10-12T12:40:00Z",
         "ceiling_seconds": 60, "requires": [], "effect": None, "decoder": {"kind": "READY_ABSENT_V3"},
         "pre_effect": None, "hold_until": None, "slots": [{"slot": "R0", "at": "2026-10-12T12:30:00Z"}]},
        {"step": "session_start", "not_before": "2026-10-12T13:28:30Z", "not_after": "2026-10-12T13:36:30Z",
         "ceiling_seconds": 420, "requires": [["core", "admission_manifest"], ["core", "post"]], "effect": reader,
         "decoder": {"kind": "SESSION_START_V3", "verifier": "session_verifier"}, "pre_effect": supervisor,
         "hold_until": "2026-10-12T13:30:30Z", "slots": [{"slot": "S1", "at": "2026-10-12T13:29:02Z"}]},
        {"step": "capture_launch", "not_before": cap_nb, "not_after": cap_na, "ceiling_seconds": 750,
         "requires": [["core", "post"], ["step", "session_start"]], "effect": cap_row,
         "decoder": k9_decoder("capture_launch", cap_row, cap_nb, cap_na), "pre_effect": None, "hold_until": None,
         "slots": [{"slot": "C1", "at": cap_start}]}]
    files = k9_files(["capture_launch"], plans, go)
    files.update({"ext/j4_hot_worker.py": "../vendor/j4_hot_worker.py", "ext/j4_codec.py": "@P_CODEX_J4_RECEIPT_CODEC_PY@",
                  "ext/session_verifier.py": "@P_CODEX_REVIEWED_SESSION_START_VERIFIER_PY@",
                  "ext/c6_bridge.py": "@P_CODEX_REVIEWED_C6_SNAPSHOT_READER_VERIFIER_PY@",
                  "ext/capacity_verifiers.py": "@P_CODEX_REVIEWED_CAPACITY_VERIFIERS_PY@",
                  "ext/ready_verifiers.py": "@P_CODEX_REVIEWED_READY_VERIFIERS_PY@",
                  "docs/bounded_readback_rule.json": "@P_APPROVED_BOUNDED_READBACK_RULE_JSON@"})
    external = dict(K9_EXTERNAL)
    external.update({"j4_codec": {"file": "ext/j4_codec.py", "identity": "verify"},
                     "session_verifier": {"file": "ext/session_verifier.py", "identity": "verify"},
                     "snapshot_reader": {"file": "ext/c6_bridge.py", "identity": "read_snapshot"},
                     "snapshot_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_snapshot"},
                     "readback_rule_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_rule"},
                     "readback_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_readback"},
                     "cap_rule": {"file": "ext/capacity_verifiers.py", "identity": "verify_rule"},
                     "cap_original": {"file": "ext/capacity_verifiers.py", "identity": "verify_original"},
                     "cap_config": {"file": "ext/capacity_verifiers.py", "identity": "verify_config"},
                     "ready_rule": {"file": "ext/ready_verifiers.py", "identity": "verify_rule"},
                     "ready_ready": {"file": "ext/ready_verifiers.py", "identity": "verify_ready"}})
    spec = {"schema": bind.SPEC_SCHEMA, "lot": "DOWN", "lane": "DOWNSTREAM_AFTER_E6", "mode": "REAL",
            "owner_deadline": owner_deadline, "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {"commit_result": "@P_UP_COMMIT_RESULT_ORIGINAL_SHA256@",
                                 "publish_launch": "@P_UP_PUBLISH_LAUNCH_ORIGINAL_SHA256@"},
            "imports": {r: {"source_lot": "UP", "request_sha256": "@P_UP_REQUEST_SHA256@",
                            "bound_sha256": "@P_UP_BOUND_SHA256@"} for r in ("commit_result", "publish_launch")},
            "files": files, "external": external, "k9": k9_section(["capture_launch"], secrets_root, networks),
            "tasks": tasks, "extended": {"steps": steps}, "bootstrap": None,
            "gate": {"scope": {"build_sha": REVISION, "image_id": IMAGE, "document_order_sha256": ORDER,
                               "release_sha256": RELEASE, "package_sha256": PACKAGE,
                               "calendar_pin_sha256": "@P_CALENDAR_PIN_SHA256@",
                               "runtime_authority_sha256": "@P_RUNTIME_AUTHORITY_SHA256@", "owner_uid": 0,
                               "manifest_directory": "@P_MANIFEST_DIRECTORY@", "session_open": "2026-10-12T13:30:00Z",
                               "not_before": "2026-10-12T10:37:30Z", "not_after": "2026-10-12T10:50:00Z",
                               "view_opens_at": "2026-10-12T10:38:00Z", "require_go_mode": "INDIVIDUAL"},
                     "journal_directory": rt.EPOCH04_JOURNAL_ROOT, "snapshot_reader": "snapshot_reader",
                     "snapshot_verifier": "snapshot_verifier",
                     "readback": {"rule": "docs/bounded_readback_rule.json", "rule_verifier": "readback_rule_verifier",
                                  "readback_verifier": "readback_verifier"}},
            "capacity": {"mode": "REAL", "lots": {"m3": "BOOT", "j": "DOWN", "activation": "CAP"},
                         "sources": {"m3": "@P_M3_ACTIVATE_PROGRAM_SHA256@", "j": J4_PROGRAMS["hot_worker"],
                                     "activation": "@P_CAPACITY_MONDAY04_PROGRAM_SHA256@"},
                         "verifiers": {"rule": "cap_rule", "original": "cap_original", "config": "cap_config"},
                         "config_path": rt.EPOCH04_CAPACITY_ROOT + "/config/capacity-final-2026-10-12.json"},
            "ready": {"mode": "REAL", "calendar_sha256": "@P_CALENDAR_PIN_SHA256@", "not_before": "2026-10-12T13:29:00Z",
                      "not_after": "2026-10-12T13:29:50Z", "max_wait_seconds": 48, "poll_seconds": 0.25,
                      "ready_path": rt.EPOCH04_READY_PATH, "verifiers": {"rule": "ready_rule", "ready": "ready_ready"}},
            "j4": {"protocol": "WARM_IMAGE10_ACTUAL_OBSERVATION", "hot_worker_source": "ext/j4_hot_worker.py",
                   "programs": dict(J4_PROGRAMS),
                   "originals": {n: "@P_J4_ORIGINAL_%s_SHA256@" % n.upper()
                                 for n in sorted(set(rt.J4_ORIGINALS) - set(rt.J4_LOT_ORIGINALS))},
                   "bridge": {"bootstrap": "bootstrap", "authorize": "authorize", "general_read": "general_read",
                              "general_verify": "general_verify"},
                   "general_authority_sha256": "@P_J4_GENERAL_AUTHORITY_SHA256@",
                   "general_source_identity": "@P_J4_GENERAL_SOURCE_IDENTITY@"}}
    return spec


# ------------------------------------------------------------------ write / validate (in-family DRAFTs)
def render(spec, comment):
    """The bytes `write` puts into lots/ (a commented DRAFT wrapper; not the bare spec `bind lot` reads)."""
    return (json.dumps({"_comment": comment, "spec": spec}, sort_keys=True, indent=1) + "\n").encode("ascii")


def write(path, spec, comment):
    raw = render(spec, comment)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        os.write(fd, raw)
    finally:
        os.close(fd)
    return rt.sha(raw)


def placeholders(value, out=None):
    out = set() if out is None else out
    if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
        out.add(value)
    elif isinstance(value, dict):
        for v in value.values():
            placeholders(v, out)
    elif isinstance(value, list):
        for v in value:
            placeholders(v, out)
    return out


SYNTHETIC_MODULE = b'''"""SYNTHETIC FILL-IN (validation of the spec shape only; never a verifier)."""
def _accept(*args):
    return None
verify = verify_approval = verify_original = verify_step = verify_rule = verify_readback = _accept
verify_config = verify_ready = verify_snapshot = read_snapshot = _accept
'''


def fill(spec, tmp):
    """Replace ONLY the declared @P_...@ placeholders with synthetic values (files -> synthetic bytes in tmp)."""
    spec = copy.deepcopy(spec)
    module = Path(tmp) / "synthetic_module.py"
    module.write_bytes(SYNTHETIC_MODULE)
    doc = Path(tmp) / "synthetic_doc.json"
    doc.write_bytes(b'{"synthetic":true}')
    for rel, local in list(spec["files"].items()):
        if local.startswith("@P_"):
            spec["files"][rel] = str(module if rel.endswith(".py") else doc)
    values = {"@P_MANIFEST_DIRECTORY@": "/var/lib/c3po-capacity-e04/payload",
              "@P_E6_DOCUMENT_PATH@": "/var/lib/c3po/r2d2-v2-k9-20261012/e6/E6_04.json",
              "@P_J4_GENERAL_SOURCE_IDENTITY@": "SYNTHETIC_FILL_IN"}

    def walk(value):
        if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
            return values.get(value, hashlib.sha256(value.encode("ascii")).hexdigest())
        if isinstance(value, dict):
            return {k: walk(v) for k, v in value.items()}
        if isinstance(value, list):
            return [walk(v) for v in value]
        return value
    return walk(spec)


def runtime_stub(lay):
    return rt.canonical({"schema": rt.RUNTIME_SCHEMA, "layout_sha256": rt.sha(rt.canonical(lay))})


def validate_up(physical=True):
    spec = build_up()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-10T12:30:00Z", LOTS, physical=physical)
    plan = json.loads((LOTS / PLANS / "plans" / "prove_launch.json").read_bytes())
    return {"status": "UP_SPEC_VALID_WITH_FILL_INS", "physical_guards": physical, "image_id": IMAGE,
            "code_revision": plan["constants"]["code_revision"], "package_sha256": plan["constants"]["package_sha256"],
            "runner_sha256": authority["files"]["ext/k9_runner04.py"], "release_sha256": plan["constants"]["release_sha256"],
            "policy_sha256": plan["constants"]["policy_sha256"], "act_b_sha256_DRAFT": plan["constants"]["act_b_sha256"],
            "go_sha256_DRAFT": plan["go_sha256"], "slots": len(authority["slots"]), "slack": slack_table(spec),
            "start_windows": start_windows(spec),
            "placeholders": sorted(placeholders(spec)) + ["ACT_B_04 (plan constants)", "K9_GO_04 (plan go_sha256)"]}


def validate_down(physical=True):
    spec = build_down()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-11T23:00:00Z", LOTS, physical=physical)
    return {"status": "DOWN_DRAFT_VALID_WITH_FILL_INS", "physical_guards": physical,
            "session_start_at": [s for s in authority["slots"] if s["target"] == "session_start"][0]["at"],
            "ready_check_at": [s for s in authority["slots"] if s["target"] == "ready_check"][0]["at"],
            "post_at": [s for s in authority["slots"] if s["target"] == "post"][0]["at"],
            "slots": len(authority["slots"]), "slack": slack_table(spec), "start_windows": start_windows(spec),
            "placeholders": sorted(placeholders(spec))}


# ------------------------------------------------------------------ REAL specs, outside the family (L-06)
def generator():
    """The family's gen_k9_plans04 (its grid tables are the only source of the elected minutes). Executed from its
    bytes into a fresh module (its import is inert; no bytecode cache is written into the family)."""
    path = LOTS / GENERATOR
    module = types.ModuleType("gen_k9_plans04_of_the_family")
    module.__file__ = str(path)
    exec(compile(path.read_bytes(), str(path), "exec"), module.__dict__)
    return module


# v3.3 (lots review F1): the signed relative names compared between the REAL UP and the REAL DOWN, and the UP dir's
# record of the capture_launch plan of its own plans run (not named by the UP spec; listed in its SHA256SUMS).
K9_REQUEST = "k9/K9_04_STEP_SET_REQUEST.json"
K9_GO = "k9/K9_GO_04.json"
RUNNER_REL = "ext/k9_runner04.py"
DOWN_CAPTURE_PLAN = "k9/capture_launch.json"
UP_CAPTURE_ANCHOR = "cross_lot/capture_launch.json"


def same_inode(a, b):
    return (a.st_dev, a.st_ino) == (b.st_dev, b.st_ino)


def sealed_roots():
    """The family root and, when it is part of a sealed delivery (a top SHA256SUMS that lists l12host/SHA256SUMS), the
    delivery root: no REAL spec may be written under either."""
    roots = [FAMILY]
    top = FAMILY.parent / "SHA256SUMS"
    try:
        if any(line.endswith("  " + FAMILY.name + "/SHA256SUMS") for line in top.read_text("ascii").splitlines()):
            roots.append(FAMILY.parent)
    except (OSError, UnicodeDecodeError):
        pass
    return [(root, os.stat(str(root))) for root in roots]


def guard_out_dir(out_dir):
    """The REAL output directory: neither it nor any existing ancestor (symlinks resolved; compared by device and
    inode, so letter case and links cannot alias) is the family root or its sealed delivery; and it does not exist."""
    target = Path(os.path.abspath(str(out_dir)))
    probe = target
    while not os.path.lexists(str(probe)):
        probe = probe.parent
    real = Path(os.path.realpath(str(probe)))
    roots = sealed_roots()
    for ancestor in [real] + list(real.parents):
        here = os.stat(str(ancestor))
        for root, info in roots:
            refuse(not same_inode(here, info), "REAL_SPEC_OUT_DIR_INSIDE_FAMILY", root.name)
    refuse(probe != target, "REAL_SPEC_OUT_DIR_EXISTS")
    return target


def recheck_created(target):
    real = Path(os.path.realpath(str(target)))
    roots = sealed_roots()
    for ancestor in [real] + list(real.parents):
        here = os.stat(str(ancestor))
        refuse(all(not same_inode(here, info) for _, info in roots), "REAL_SPEC_OUT_DIR_INSIDE_FAMILY")


def read_file(path, limit=rt.LIMIT):
    p = Path(path)
    refuse(p.is_absolute() and not p.is_symlink() and p.is_file(), "REAL_INPUT_NOT_A_REGULAR_FILE", p.name)
    raw = p.read_bytes()
    refuse(0 < len(raw) <= limit, "REAL_INPUT_SIZE_INVALID", p.name)
    return raw


def real_plans(plans_dir, go_path):
    """The REAL K9 inputs: a gen_k9_plans04 output of an ELECTED grid, byte-equal to its manifest, with the family's
    runner, the certified release/policy, an act B that is not the draft placeholder, and the manifest's GO."""
    root = Path(plans_dir)
    refuse(root.is_absolute() and root.is_dir() and not root.is_symlink(), "REAL_PLANS_DIR_INVALID")
    m_raw = read_file(root / "K9_04_STEP_SET_MANIFEST.json")
    m = rt.strict(m_raw, kind=Refused)
    refuse(m.get("schema") == "K9_04_STEP_SET_MANIFEST_V1" and m.get("image_id") == IMAGE, "REAL_PLANS_MANIFEST_INVALID")
    refuse(m.get("synthetic") is False, "REAL_PLANS_SYNTHETIC")
    grid = m.get("grid")
    refuse(type(grid) is dict and grid.get("id") in ELECTED_GRIDS, "REAL_PLANS_GRID_NOT_ELECTED",
           grid.get("id") if type(grid) is dict else None)
    gen = generator()
    refuse(grid == gen.grid_block(grid["id"]), "REAL_PLANS_GRID_NOT_THIS_GENERATOR", grid["id"])
    request_raw = read_file(root / "K9_04_STEP_SET_REQUEST.json")
    request = rt.strict(request_raw, kind=Refused)
    refuse(rt.sha(request_raw) == m.get("request_sha256") and request.get("grid") == grid
           and request.get("synthetic") is False, "REAL_PLANS_REQUEST_NOT_THE_MANIFEST_ONE")
    table = {row["operation"]: row for row in grid["slots"]}
    refuse(type(m.get("steps")) is dict and set(m["steps"]) == set(gen.STEPS) == set(table), "REAL_PLANS_STEPS_INVALID")
    constants = None
    for op, step in m["steps"].items():
        raw = read_file(root / "plans" / (op + ".json"))
        plan = rt.strict(raw, kind=Refused)
        refuse(rt.sha(raw) == step["plan_sha256"] and plan.get("request_sha256") == m["request_sha256"]
               and plan.get("go_sha256") == m.get("go_sha256"), "REAL_PLAN_NOT_THE_MANIFEST_ONE", op)
        row = plan.get("step_row")
        refuse(type(row) is dict and row.get("grid") == grid and row.get("starts_at") == table[op]["starts_at_utc"]
               == step["starts_at_utc"], "REAL_PLAN_NOT_ON_THE_GRID", op)
        refuse(constants is None or plan.get("constants") == constants, "REAL_PLANS_CONSTANTS_DIFFER", op)
        constants = plan.get("constants")
    runner = (LOTS / RUNNER).read_bytes()
    refuse(m["runner"]["sha256"] == rt.sha(runner) and read_file(root / "tools" / m["runner"]["name"]) == runner,
           "REAL_PLANS_RUNNER_NOT_THE_FAMILY_ONE")
    refuse(constants["release_sha256"] == RELEASE and constants["policy_sha256"] == POLICY,
           "REAL_PLANS_RELEASE_POLICY_NOT_CERTIFIED")
    refuse(constants["act_b_sha256"] not in (rt.sha((LOTS / DRAFT_ACT_B).read_bytes()), gen.SYNTHETIC["act_b"]),
           "REAL_PLANS_ACT_B_IS_THE_DRAFT")
    go = read_file(go_path)
    refuse(rt.sha(go) == m.get("go_sha256"), "REAL_GO_NOT_THE_MANIFEST_ONE")
    refuse(rt.sha(go) not in (rt.sha((LOTS / DRAFT_GO).read_bytes()), rt.sha(gen.SYNTHETIC_GO)), "REAL_GO_IS_THE_DRAFT")
    return m


def substitute(spec, values):
    """Every @P_...@ of the lot from `values` (a placeholder that names a file -> that file's absolute path, its bytes
    copied at write); no other key, none left."""
    wanted = placeholders(spec)
    refuse(type(values) is dict and all(type(k) is str and type(v) is str and v and not v.startswith("@P_")
                                        for k, v in values.items()), "REAL_VALUES_INVALID")
    refuse(not set(values) - wanted, "REAL_VALUES_UNKNOWN_PLACEHOLDER", sorted(set(values) - wanted)[:1] or None)
    refuse(not wanted - set(values), "REAL_SPEC_PLACEHOLDER_UNFILLED", sorted(wanted - set(values))[:1] or None)
    file_placeholders = {v for v in spec["files"].values() if v in wanted}
    for name in file_placeholders:
        read_file(values[name])

    def walk(value):
        if isinstance(value, str) and value in wanted:
            return values[value]
        if isinstance(value, dict):
            return {k: walk(v) for k, v in value.items()}
        if isinstance(value, list):
            return [walk(v) for v in value]
        return value
    out = walk(spec)
    refuse(not placeholders(out), "REAL_SPEC_PLACEHOLDER_UNFILLED")
    return out


def validation_instant(owner_deadline):
    """prepared_at used only to validate (the REQUEST is built later by `bind_l12host.py lot --prepared-at`)."""
    return rt.iso(rt.stamp(owner_deadline, Refused) - timedelta(seconds=60))


def windows_or_refuse(spec):
    windows = start_windows(spec)
    bad = [r["slot"] for r in windows if not r["ok"]]
    refuse(not bad, "REAL_SLOT_START_WINDOW_NOT_ALLOWED", bad[:1] or None)
    return windows


def write_file(target, rel, raw):
    path = target / rel
    if path.parent != target and not path.parent.exists():
        os.mkdir(str(path.parent), 0o700)
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        view = memoryview(raw)
        while view:
            view = view[os.write(fd, view):]
        os.fsync(fd)
    finally:
        os.close(fd)
    return rt.sha(raw)


def write_real(lot, out_dir, *, plans_dir, go, layout_path, secrets_root, networks, owner_deadline, values_path,
               up_real_dir=None):
    """L-06: the REAL SPEC of a lot and its files in a NEW directory outside the sealed family. v3.3 (F1): the DOWN
    needs `up_real_dir` (the written REAL UP dir) and is refused unless its K9 request, GO, runner and capture_launch
    plan bytes are the UP's and its grid id is the UP's; the UP dir records its capture_launch plan for that check."""
    target = guard_out_dir(out_dir)
    refuse(lot in ("UP", "DOWN"), "REAL_LOT_INVALID")
    refuse(lot == "UP" or up_real_dir is not None, "REAL_DOWN_NEEDS_THE_UP_REAL_DIR")
    refuse(lot == "DOWN" or up_real_dir is None, "REAL_UP_TAKES_NO_UP_REAL_DIR")
    refuse(type(networks) is dict and set(networks) == set(NETWORK_CLASSES), "REAL_NETWORKS_NOT_THE_THREE_CLASSES")
    rt.stamp(owner_deadline, Refused)
    lay = rt.validate_layout(bind.loose_json(layout_path), Refused)
    m = real_plans(plans_dir, go)
    plans_abs, go_abs = str(Path(plans_dir)), str(Path(go))
    if lot == "UP":
        spec = build_up(secrets_root, networks, plans=plans_abs, go=go_abs, owner_deadline=owner_deadline)
    else:
        spec = build_down(secrets_root, networks, plans=plans_abs, go=go_abs, lay=lay, owner_deadline=owner_deadline)
    spec = substitute(spec, bind.loose_json(values_path))
    windows = windows_or_refuse(spec)
    prepared = validation_instant(owner_deadline)
    stub = runtime_stub(lay)
    authority_raw, request_raw, authority, q, extra = bind.build_lot(spec, lay, stub, prepared, LOTS, physical=True)
    refuse(rt.sha(extra["k9/K9_04_STEP_SET_REQUEST.json"]) == m["request_sha256"]
           and rt.sha(extra["k9/K9_GO_04.json"]) == m["go_sha256"]
           and all(rt.sha(extra[rel]) == m["steps"][op]["plan_sha256"] for op, rel in spec["k9"]["plans"].items()),
           "REAL_K9_BYTES_CHANGED_WHILE_READ")
    cross = anchor = None
    if lot == "UP":
        anchor = read_file(Path(plans_dir) / "plans" / "capture_launch.json")
        refuse(rt.sha(anchor) == m["steps"]["capture_launch"]["plan_sha256"], "REAL_K9_BYTES_CHANGED_WHILE_READ")
    else:
        cross = down_matches_up(up_real_dir, layout_path, extra, m)
    name = lot + ".SPEC.json"
    bare = copy.deepcopy(spec)
    bare["files"] = {rel: rel for rel in spec["files"]}
    spec_raw = (json.dumps(bare, sort_keys=True, indent=1) + "\n").encode("ascii")
    os.mkdir(str(target), 0o700)
    recheck_created(target)
    written = {rel: write_file(target, rel, raw) for rel, raw in sorted(extra.items())}
    if anchor is not None:
        written[UP_CAPTURE_ANCHOR] = write_file(target, UP_CAPTURE_ANCHOR, anchor)
    written[name] = write_file(target, name, spec_raw)
    again = bind.build_lot(bind.loose_json(target / name), lay, stub, prepared, target, physical=True)
    refuse(again[0] == authority_raw and again[1] == request_raw, "REAL_SPEC_REREAD_DIFFERS")
    sums = "".join("%s  %s\n" % (written[k], k) for k in sorted(written)).encode("ascii")
    sums_sha = write_file(target, "SHA256SUMS", sums)
    out = {"status": "REAL_SPEC_WRITTEN_OUTSIDE_THE_FAMILY", "lot": lot, "out_dir": str(target), "spec": name,
           "spec_sha256": written[name], "sha256sums_sha256": sums_sha, "files": len(written),
           "grid": m["grid"]["id"], "grid_slots_sha256": m["grid"]["slots_sha256"], "plans_manifest_request_sha256":
           m["request_sha256"], "go_sha256": m["go_sha256"], "layout_sha256": rt.sha(rt.canonical(lay)),
           "owner_deadline": owner_deadline, "validated_physical": True, "start_windows": windows,
           "slack": slack_table(spec)}
    if lot == "UP":
        out["capture_launch_anchor"] = {"file": UP_CAPTURE_ANCHOR, "sha256": written[UP_CAPTURE_ANCHOR]}
    else:
        out["up_cross_check"] = cross
    return out


def real_dir(out_dir):
    """A written REAL dir, integrity only: (absolute target, SHA256SUMS bytes, {rel: sha256}); SHA256SUMS lists every
    file exactly and every listed byte matches. v3.3 (lots review LOW 6): a relative DIR is made absolute, as `write`
    does, and a DIR that is not a real directory is refused as such."""
    target = Path(os.path.abspath(str(out_dir)))
    refuse(target.is_dir() and not target.is_symlink(), "REAL_SPEC_DIR_NOT_A_DIRECTORY")
    sums = read_file(target / "SHA256SUMS")
    listed = {}
    for line in sums.decode("ascii").splitlines():
        digest, _, rel = line.partition("  ")
        refuse(len(digest) == 64 and rel and rel not in listed, "REAL_DIR_SUMS_INVALID")
        listed[rel] = digest
    present = {p.relative_to(target).as_posix() for p in target.rglob("*") if not p.is_dir()} - {"SHA256SUMS"}
    refuse(set(listed) == present, "REAL_DIR_FILE_SET_MISMATCH")
    refuse(all(rt.sha(read_file(target / rel)) == digest for rel, digest in listed.items()), "REAL_DIR_BYTES_MISMATCH")
    return target, sums, listed


def check_real(out_dir, layout_path):
    """Re-checks a written REAL dir; writes nothing."""
    target, sums, listed = real_dir(out_dir)
    names = [n for n in listed if n.endswith(".SPEC.json")]
    refuse(len(names) == 1 and names[0] in ("UP.SPEC.json", "DOWN.SPEC.json"), "REAL_DIR_SPEC_INVALID")
    spec = bind.loose_json(target / names[0])
    refuse(spec.get("lot") + ".SPEC.json" == names[0] and not placeholders(spec), "REAL_DIR_SPEC_INVALID")
    request_raw = read_file(target / K9_REQUEST)
    request = rt.strict(request_raw, kind=Refused)
    grid = request.get("grid")
    refuse(type(grid) is dict and grid.get("id") in ELECTED_GRIDS and grid == generator().grid_block(grid["id"]),
           "REAL_PLANS_GRID_NOT_ELECTED")
    if spec["lot"] == "UP":
        # v3.3 (F1): the UP dir carries the capture_launch plan of ITS plans run, bound to its request and GO
        refuse(UP_CAPTURE_ANCHOR in listed, "REAL_UP_CAPTURE_ANCHOR_INVALID")
        anchor = rt.strict(read_file(target / UP_CAPTURE_ANCHOR), kind=Refused)
        refuse(anchor.get("k9_operation") == "capture_launch" and anchor.get("request_sha256") == rt.sha(request_raw)
               and anchor.get("go_sha256") == rt.sha(read_file(target / K9_GO))
               and type(anchor.get("step_row")) is dict and anchor["step_row"].get("grid") == grid,
               "REAL_UP_CAPTURE_ANCHOR_INVALID")
    windows = windows_or_refuse(spec)
    lay = rt.validate_layout(bind.loose_json(layout_path), Refused)
    bind.build_lot(spec, lay, runtime_stub(lay), validation_instant(spec["owner_deadline"]), target, physical=True)
    return {"status": "REAL_SPEC_DIR_VALID", "lot": spec["lot"], "spec_sha256": listed[names[0]],
            "sha256sums_sha256": rt.sha(sums), "files": len(listed), "grid": grid["id"],
            "layout_sha256": rt.sha(rt.canonical(lay)), "start_windows": windows}


def down_matches_up(up_real_dir, layout_path, extra, m):
    """v3.3 (lots review F1, MEDIUM): the REAL DOWN uses byte-identical K9 request, GO, runner and capture_launch plan
    bytes as the UP REAL spec, and the same grid id. The comparisons come first (each mismatch has its own code), then
    the whole UP dir is re-validated (check_real). Writes nothing."""
    try:
        up_dir, _, listed = real_dir(up_real_dir)
    except rt.Hold as error:
        raise Refused("REAL_DOWN_UP_DIR_INVALID", rt.safe_code(error)) from None
    refuse("UP.SPEC.json" in listed and all(rel in listed for rel in (K9_REQUEST, K9_GO, RUNNER_REL, UP_CAPTURE_ANCHOR)),
           "REAL_DOWN_UP_DIR_NOT_AN_UP_REAL_DIR")
    up = {rel: read_file(up_dir / rel) for rel in (K9_REQUEST, K9_GO, RUNNER_REL, UP_CAPTURE_ANCHOR)}
    up_grid = rt.strict(up[K9_REQUEST], kind=Refused).get("grid")
    up_grid_id = up_grid.get("id") if type(up_grid) is dict else None
    refuse(up_grid_id == m["grid"]["id"], "REAL_DOWN_GRID_NOT_THE_UP_ONE", [up_grid_id, m["grid"]["id"]])
    refuse(up[K9_REQUEST] == extra[K9_REQUEST], "REAL_DOWN_K9_REQUEST_NOT_THE_UP_ONE")
    refuse(up[K9_GO] == extra[K9_GO], "REAL_DOWN_K9_GO_NOT_THE_UP_ONE")
    refuse(up[RUNNER_REL] == extra[RUNNER_REL], "REAL_DOWN_RUNNER_NOT_THE_UP_ONE")
    refuse(up[UP_CAPTURE_ANCHOR] == extra[DOWN_CAPTURE_PLAN], "REAL_DOWN_CAPTURE_PLAN_NOT_THE_UP_ONE")
    try:
        checked = check_real(str(up_dir), layout_path)
    except rt.Hold as error:
        raise Refused("REAL_DOWN_UP_DIR_INVALID", rt.safe_code(error)) from None
    refuse(checked["lot"] == "UP", "REAL_DOWN_UP_DIR_NOT_AN_UP_REAL_DIR")
    return {"up_real_dir": str(up_dir), "up_spec_sha256": checked["spec_sha256"],
            "up_sha256sums_sha256": checked["sha256sums_sha256"], "grid": up_grid_id,
            "k9_request_sha256": rt.sha(up[K9_REQUEST]), "go_sha256": rt.sha(up[K9_GO]),
            "runner_sha256": rt.sha(up[RUNNER_REL]), "capture_launch_plan_sha256": rt.sha(up[UP_CAPTURE_ANCHOR]),
            "byte_identical": True}


UP_COMMENT = ["L12-HOST v3.1 UP lot SPEC, REAL values; build_specs.py builds it from the gen_k9_plans04 output.",
              "DRAFT until Saturday: act B 04 and the K9 04 GO (plan bytes and hashes change; regenerate the plans with",
              "the real files and rebuild), ext/k9_verifiers04.py (Codex-reviewed REAL verifiers), D-NET network names,",
              "secrets_root (REQUEST parameter, decision pending Codex). Not signed data until the owner's Assino.",
              "v3.1: every LAUNCH row's inner KILL is budget - 65 s (generator: budget - 35 s) so the effect may start up",
              "to 45 s after its instant (30 s beyond the 15 s gate allowance); Codex ruling on the runner's DEADLINE",
              "receipt window (55 s -> 25 s + lateness) requested (CONTRACT 9.3)."]
DOWN_COMMENT = ["L12-HOST v3.1 DOWN lot SPEC DRAFT (B3: no PRE_OPEN reader start; one late session start claim at",
                "10:29:02 BRT; K9 capture as an EXTENDED step; v3.1 early read-only ready_check R0 at 09:30 BRT).",
                "Every @P_...@ is unknown today. Supervisor state root /var/lib/c3po-bar/supervisor-e04 and config",
                "/etc/c3po-reader-e04/supervisor are PROPOSALS for INSTALL_TREE04. J budget 300 s and the J2/J3 instants",
                "are drafts. Not signed data.",
                "Lots patch v3.4 (L-02): PO post 06:01:30 BRT (09:01:30Z, window [09:01:00Z, 09:03:30Z)), 30 s after E6;",
                "[at, at + 60 s] + 45 s ends 06:03:15, before the engine's first forbidden second 06:03:40 (margin 130 s)."]


def main(argv):
    if argv == ["write"]:
        out = {"UP.SPEC.json": write(LOTS / "UP.SPEC.json", build_up(), UP_COMMENT),
               "DOWN.SPEC.DRAFT.json": write(LOTS / "DOWN.SPEC.DRAFT.json", build_down(), DOWN_COMMENT)}
    elif argv == ["validate"]:
        out = {"UP": validate_up(), "DOWN": validate_down()}
    else:
        p = argparse.ArgumentParser(prog="build_specs.py", description=__doc__,
                                    formatter_class=argparse.RawDescriptionHelpFormatter)
        p.add_argument("command", choices=("write", "validate"))
        p.add_argument("--out-dir", required=True)
        p.add_argument("--layout", required=True)
        for flag in ("--lot", "--plans-dir", "--go", "--secrets-root", "--owner-deadline", "--values", "--up-real-dir"):
            p.add_argument(flag)
        p.add_argument("--network", action="append", default=[])
        a = p.parse_args(argv)
        try:
            if a.command == "validate":
                refuse(not any((a.lot, a.plans_dir, a.go, a.secrets_root, a.owner_deadline, a.values, a.network,
                                a.up_real_dir)), "ARGUMENTS_INVALID")
                out = check_real(os.path.abspath(a.out_dir), a.layout)          # v3.3 (LOW 6): absolute, as write
            else:
                refuse(all((a.lot, a.plans_dir, a.go, a.secrets_root, a.owner_deadline, a.values)), "ARGUMENTS_INVALID")
                pairs = [n.split("=", 1) for n in a.network]
                refuse(all(len(x) == 2 for x in pairs) and len(pairs) == len(dict(pairs)), "REAL_NETWORKS_NOT_THE_THREE_CLASSES")
                out = write_real(a.lot, a.out_dir, plans_dir=os.path.abspath(a.plans_dir), go=os.path.abspath(a.go),
                                 layout_path=a.layout, secrets_root=a.secrets_root, networks=dict(pairs),
                                 owner_deadline=a.owner_deadline, values_path=a.values,
                                 up_real_dir=os.path.abspath(a.up_real_dir) if a.up_real_dir else None)
        except (ValueError, OSError, KeyError, TypeError, AttributeError) as error:
            print(json.dumps({"status": "REFUSED", "command": a.command, "code": rt.safe_code(error)
                              if not isinstance(error, OSError) else "REAL_IO_" + type(error).__name__.upper(),
                              "detail": getattr(error, "detail", None)}, sort_keys=True))
            return 2
    print(json.dumps(out, sort_keys=True, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
