"""L12-HOST v3 lot SPECs of epoch 04 (Fable, Mac, offline): UP.SPEC.json filled with REAL values and the DOWN draft.

    python3 -I -B lots/build_specs.py write       -> lots/UP.SPEC.json, lots/DOWN.SPEC.DRAFT.json (refuses to overwrite)
    python3 -I -B lots/build_specs.py validate    -> both specs through bind_l12host.build_lot in PHYSICAL mode (every
                                                     v3 rule and epoch-04 guard) after replacing ONLY the declared
                                                     placeholders with synthetic fill-ins; prints the summaries.

UP (Saturday 10/10): the real image sha256:bf37cec9..., revision de96aee9..., package 43db2b96..., runner04 e9be2b30...
(full-hash name), the 11 UP plans generated by Codex's gen_k9_plans04 2b08ee13 with the REAL release 5fd6eadb... and
policy 6757e791... (lots/up_plans_DRAFT_actB_GO_pending, generated from lots/up_inputs). The rows are the generator's
manifest rows converted to the v3 CONTAINER shape (network per class, env files and emitter mount from the secrets
root REQUEST parameter). Placeholders that stay until Saturday / Codex:
    act B 04 and the K9 04 GO     -> the plan bytes (and so every plan hash) are DRAFT: regenerate with the real files
    ext/k9_verifiers04.py          -> the Codex-reviewed K9 approval/original/step verifiers (REAL, pinned)
    networks (D-NET)               -> PROVIDER bridge (K9W epoch-03 constant), DATABASE* c3po_default (compose default)
    secrets_root                   -> REQUEST parameter; default = the generator's epoch-03 root (Codex root closure:
                                      CONDITIONAL_READONLY_REUSE_MATERIAL_ONLY); INSTALL_TREE04 rev 2 also creates
                                      the epoch-04 copies under /var/lib/c3po/r2d2-v2-k9-20261012/secrets.
DOWN (Sunday 11/10, B3): e6, J (J1/J2/J3 of ONE attempt), post in the core; the late session start and the K9 capture as
EXTENDED steps; gate (bounded readback r1), capacity and READY sections. Every unknown is an @P_...@ placeholder.
"""
import copy
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile

LOTS = Path(__file__).resolve().parent
FAMILY = LOTS.parent
sys.path.insert(0, str(FAMILY / "vendor"))
sys.path.insert(0, str(FAMILY))
import l12host_runtime as rt      # noqa: E402
import bind_l12host as bind       # noqa: E402

PLANS = "up_plans_DRAFT_actB_GO_pending"
GEN_SECRETS_ROOT = "/var/lib/c3po/r2d2-v2-k9-20261005/secrets"
NETWORKS = {"PROVIDER": "bridge", "DATABASE": "c3po_default", "DATABASE_AND_PROVIDER": "c3po_default"}
D1 = "09de76e5a2ee54fdcdfa477b0f8df101fcda761b7f416e4308e29c0235e51c2a"
ORDER = "70cb947fc5276949ca3f08d53cfaf79873463a83f36a64859056d7616fcdf9d3"
IMAGE = "sha256:bf37cec9f4f93e129543235a567a2de5daad0c8116086e2b176069e497defba3"
REVISION = "de96aee90a26e9587663ba7a1f6e55a592afcd20"
PACKAGE = "43db2b969fe113594fafe4a9e0cabec1f80ada9f8ab9ee5852677d65e2ec716a"
RELEASE = "5fd6eadbf8c1c899598e23c52e98599fe9cc990bd33a182cc363d2c05c5784ab"
POLICY = "6757e79112770f948b73770f6b6b87f209930afe8cd00f9517d378055e0d2d92"
VERIFIERS_PLACEHOLDER = "@P_CODEX_REVIEWED_K9_VERIFIERS04_PY@"
CORE = (("prove", "prove_launch", []), ("collect", "collect_launch", ["prove"]),
        ("commit_result", "commit_launch", ["collect"]), ("publish_launch", "publish_launch", ["commit_result"]))
J4_PROGRAMS = {"hot_runtime": "55e2cc2c97c73d0b7ae9ad8289b9cf7ff28dfb26321690b5ea40cb21438921bc",
               "hot_worker": "0edb64f45b8a4e31e64aa274e778566106e3549d7e8fe2ab8d746dd1b751d8fa",
               "hot_watchdog": "12ce74398c8bb5d0a48af8d528dc40be8703860b7cd47223328cdb9e6c073def",
               "finite_batch": "809a816d4179ee889531bfc2d270e193508f0d1a31d7a30a48159151f80dbeec",
               "folder_veto": "8d63f75cad847da5d4f5ede7dedba24b64ea296d86bad67d16fb5f8e02271b18",
               "veto_emitter": "b3ea98c4e35d749946f95b32b7dbf8e726779c70fa9f5e5001572a3f24045817",
               "config_finalizer": "45dce62d7f8e17cb3d93bfefa480352778234cc9ee88c632ad9a5268b732a30d",
               "consumer_codec": "57933d7cf4d79b62ab1c7b291b8c460a743864c78d5ad5a3111c9b2c0b76f2b6",
               "j_slot": "d4c029cabf895276e81dec38f38b387be9c85f03d4e26926846d3c8c8505db04",
               "authority_bridge": "@P_J4_AUTHORITY_BRIDGE_REAL_SHA256@"}


def z(text):
    return text.replace("+00:00", "Z")


def at_minus(text, seconds):
    return rt.iso(rt.stamp(z(text)) - __import__("datetime").timedelta(seconds=seconds))


def at_plus(text, seconds):
    return rt.iso(rt.stamp(z(text)) + __import__("datetime").timedelta(seconds=seconds))


def manifest():
    return json.loads((LOTS / PLANS / "K9_04_STEP_SET_MANIFEST.json").read_bytes())


DOCKER_MARGIN = 20                        # l12host_effect.DOCKER_MARGIN_SECONDS
SLACK_KILL = DOCKER_MARGIN + rt.GATE_ALLOWANCE_SECONDS + rt.EFFECT_LATENESS_SLACK_SECONDS     # 65 s


def kill_with_slack(step):
    """v3.1 (finding 8): the inner KILL of an UP row leaves >= 30 s of slack beyond (effect floor + gate allowance):
    KILL = min(generator KILL, budget - 20 - 15 - 30). For a LAUNCH step the generator's KILL is budget - 35 (the
    runner stops itself at run_not_after - 60 = start + budget - 90 and has < 55 s to write its DEADLINE receipt);
    with KILL = budget - 65 that window is 25 s + the effect lateness (Codex ruling requested; CONTRACT 9.3)."""
    return min(step["l12_effect"]["docker"]["timeout_seconds"], step["budget_seconds"] - SLACK_KILL)


def convert(step, secrets_root, networks, *, slack=True):
    """The generator's K9STEP row (v1 shape) -> the v3 CONTAINER row: network per class, env files and the emitter
    mount re-rooted at the secrets root parameter, receipt FILE, no `mode` (ATTACHED is the only mode). v3.1: UP rows
    get the slack KILL (kill_with_slack); the DOWN capture keeps the generator's KILL (its shell ceiling 750 s is above
    the plan budget 690 s and already leaves 30 s)."""
    e = step["l12_effect"]
    d = e["docker"]
    swap = lambda p: secrets_root + p[len(GEN_SECRETS_ROOT):] if p.startswith(GEN_SECRETS_ROOT + "/") else p
    cls = step["network_class"]
    return {"kind": "CONTAINER", "docker": {
        "name": d["name"], "labels": d["labels"], "network": "none" if cls == "NONE" else networks[cls],
        "env_files": [swap(p) for p in d["env_files"]], "env": d["env"],
        "mounts": [dict(m, source=swap(m["source"])) for m in d["mounts"]], "tmpfs": d["tmpfs"], "workdir": d["workdir"],
        "image_id": d["image_id"], "command": d["command"],
        "timeout_seconds": kill_with_slack(step) if slack else d["timeout_seconds"]},
        "receipt": {"source": "FILE", "path": e["receipt"]["path"]}}


def slack_table(spec):
    """budget floor vs effect lateness of every K9 row of a spec (CONTRACT 9.3)."""
    rows = []
    for t in spec["tasks"]:
        d = t["effect"].get("docker")
        if d:
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": t["operation"], "budget": t["budget_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": t["budget_seconds"] - floor,
                         "slack_beyond_allowance": t["budget_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS})
    for s in (spec["extended"] or {}).get("steps", []):
        d = (s["effect"] or {}).get("docker")
        if d:
            extra = 2 * rt.GATE_ALLOWANCE_SECONDS if s["step"] == "capture_launch" else 0
            floor = d["timeout_seconds"] + DOCKER_MARGIN
            rows.append({"target": s["step"], "budget": s["ceiling_seconds"], "kill": d["timeout_seconds"],
                         "effect_floor": floor, "max_effect_lateness": s["ceiling_seconds"] - floor - extra,
                         "slack_beyond_allowance": s["ceiling_seconds"] - floor - rt.GATE_ALLOWANCE_SECONDS - extra})
    return rows


def k9_decoder(op, row, nb, na, mode="REAL"):
    return {"kind": "K9_STEP_V1", "mode": mode, "runner_source": "ext/k9_runner04.py", "step_plan": "k9/%s.json" % op,
            "k9_request": "k9/K9_04_STEP_SET_REQUEST.json", "k9_go": "k9/K9_GO_04.json",
            "provenance_binding_sha256": rt.sha(rt.canonical(row)), "phase_not_before": nb, "phase_not_after": na,
            "verifiers": {"approval": "k9_approval", "original": "k9_original"}}


def k9_files(ops):
    files = {"ext/k9_runner04.py": "k9tools/k9_runner04.py",
             "k9/K9_04_STEP_SET_REQUEST.json": PLANS + "/K9_04_STEP_SET_REQUEST.json",
             "k9/K9_GO_04.json": "up_inputs/K9_GO_04.PLACEHOLDER.txt",
             "ext/k9_verifiers04.py": VERIFIERS_PLACEHOLDER}
    for op in ops:
        files["k9/%s.json" % op] = PLANS + "/plans/%s.json" % op
    return files


def k9_section(ops, secrets_root, networks):
    return {"runner_source": "ext/k9_runner04.py", "request": "k9/K9_04_STEP_SET_REQUEST.json", "go": "k9/K9_GO_04.json",
            "plans": {op: "k9/%s.json" % op for op in ops}, "networks": dict(networks), "secrets_root": secrets_root}


K9_EXTERNAL = {"k9_approval": {"file": "ext/k9_verifiers04.py", "identity": "verify_approval"},
               "k9_original": {"file": "ext/k9_verifiers04.py", "identity": "verify_original"},
               "k9_step": {"file": "ext/k9_verifiers04.py", "identity": "verify_step"}}


# ------------------------------------------------------------------ UP
def build_up(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS):
    m = manifest()
    steps = m["steps"]
    tasks, ops = [], []
    for i, (core, op, requires) in enumerate(CORE):
        s = steps[op]
        start = z(s["starts_at_utc"])
        nb, na = at_minus(start, 30), at_plus(start, s["budget_seconds"])
        row = convert(s, secrets_root, networks)
        tasks.append({"operation": core, "not_before": nb, "not_after": na, "budget_seconds": s["budget_seconds"],
                      "requires": requires, "slots": [{"slot": "P%d" % (i + 1), "at": start}], "effect": row,
                      "decoder": k9_decoder(op, row, nb, na), "image_go_sha256": None, "image_proposal_sha256": None})
        ops.append(op)
    ext = []
    for j, (name, (kind, op, requires)) in enumerate(rt.EXTENDED_TABLE["UPSTREAM_P"].items()):
        s = steps[op]
        start = z(s["starts_at_utc"])
        ext.append({"step": name, "not_before": at_minus(start, 30), "not_after": at_plus(start, s["budget_seconds"]),
                    "ceiling_seconds": s["budget_seconds"], "requires": [list(r) for r in requires],
                    "effect": convert(s, secrets_root, networks), "decoder": {"kind": "K9_EXT_STEP_V3", "verifier": "k9_step"},
                    "pre_effect": None, "hold_until": None, "slots": [{"slot": "X%d" % (j + 1), "at": start}]})
        ops.append(op)
    return {"schema": bind.SPEC_SCHEMA, "lot": "UP", "lane": "UPSTREAM_P", "mode": "REAL",
            "owner_deadline": "2026-10-10T13:20:00Z", "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {}, "imports": {}, "files": k9_files(ops), "external": dict(K9_EXTERNAL),
            "k9": k9_section(ops, secrets_root, networks), "tasks": tasks, "extended": {"steps": ext},
            "bootstrap": None, "gate": None, "capacity": None, "ready": None, "j4": None}


# ------------------------------------------------------------------ DOWN (draft, B3)
def layout():
    return bind.loose_json(LOTS / "layout.e04.DRAFT.json")


def build_down(secrets_root=GEN_SECRETS_ROOT, networks=NETWORKS):
    m = manifest()
    lay = layout()
    docker = lay["binaries"]["docker"]
    reader, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-reader.service"), {
        "@HOST_DATA_ROOT@": "/mnt/day-d-data", "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT,
        "@HOST_CAPACITY_ROOT@": rt.EPOCH04_CAPACITY_ROOT, "@HOST_CONFIG_DIR@": rt.EPOCH04_READER_CONFIG,
        "@IMAGE_ID@": IMAGE, "@NETWORK@": networks["DATABASE"], "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.READER_NAME, "SESSION_READER", lay, [("c3po-reader", rt.READER_NAME)])
    sup_cfg = rt.EPOCH04_READER_CONFIG + "/supervisor"
    supervisor, _, _ = bind.unit_row(str(FAMILY / "reference" / "c3po-massive.service"), {
        "@HOST_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT, "@HOST_STATE_ROOT@": rt.EPOCH04_SUPERVISOR_STATE,
        "@HOST_CONFIG_DIR@": sup_cfg, "@IMAGE_ID@": IMAGE, "@NETWORK@": networks["DATABASE"],
        "@CONTAINER_JOURNAL_ROOT@": rt.EPOCH04_JOURNAL_ROOT},
        rt.SUPERVISOR_NAME, "SUPERVISOR", lay,
        [("c3po-massive", rt.SUPERVISOR_NAME), ("DOCKER_CONFIG=" + sup_cfg + "/docker-cli", "DOCKER_CONFIG=" + lay["docker_config"])])
    cap = m["steps"]["capture_launch"]
    cap_start = z(cap["starts_at_utc"])
    cap_row = convert(cap, secrets_root, networks, slack=False)
    cap_nb, cap_na = at_minus(cap_start, 30), at_plus(cap_start, 750)
    task = lambda op, slots, req, eff, dec, nb, na, budget: {
        "operation": op, "not_before": nb, "not_after": na, "budget_seconds": budget, "requires": req,
        "slots": slots, "effect": eff, "decoder": dec, "image_go_sha256": None, "image_proposal_sha256": None}
    j_argv = ["--registry-record-base64", rt.J4_REGISTRY_TOKEN, "--mode", "REAL"]
    tasks = [
        task("e6", [{"slot": "E6", "at": "2026-10-12T09:01:00Z"}], ["commit_result", "publish_launch"],
             {"kind": "READBACK", "files": [{"path": "@P_E6_DOCUMENT_PATH@", "sha256": "@P_E6_DOCUMENT_SHA256@",
                                             "mode": 256, "uid": 0}]},
             {"kind": "READBACK_V3"}, "2026-10-12T09:00:30Z", "2026-10-12T09:03:00Z", 60),
        task("admission_manifest", [{"slot": "J1", "at": "2026-10-12T10:38:00Z"}, {"slot": "J2", "at": "2026-10-12T10:41:00Z"},
                                    {"slot": "J3", "at": "2026-10-12T10:44:00Z"}], ["e6"],
             {"kind": "HOST_PROGRAM", "source": "ext/j4_hot_worker.py", "argv": j_argv},
             {"kind": "HOT_J_V1", "verifier": "j4_codec"}, "2026-10-12T10:37:30Z", "2026-10-12T10:50:00Z", 300),
        task("post", [{"slot": "PO", "at": "2026-10-12T09:03:00Z"}], ["publish_launch"],
             {"kind": "CHAIN_READBACK", "source_lot": "UP", "source_request_sha256": "@P_UP_REQUEST_SHA256@",
              "source_bound_sha256": "@P_UP_BOUND_SHA256@", "steps": list(rt.EXTENDED_TABLE["UPSTREAM_P"])},
             {"kind": "CHAIN_READBACK_V3"}, "2026-10-12T09:02:30Z", "2026-10-12T09:05:00Z", 60)]
    steps = [
        # v3.1 (finding 2): the early read-only absence check of the ready file, 09:30 BRT (a person has ~1 h to clear
        # a leftover before the 10:29:02 BRT session start, which re-checks absence itself before the supervisor).
        {"step": "ready_check", "not_before": "2026-10-12T12:29:30Z", "not_after": "2026-10-12T12:40:00Z",
         "ceiling_seconds": 60, "requires": [], "effect": None, "decoder": {"kind": "READY_ABSENT_V3"},
         "pre_effect": None, "hold_until": None, "slots": [{"slot": "R0", "at": "2026-10-12T12:30:00Z"}]},
        {"step": "session_start", "not_before": "2026-10-12T13:28:30Z", "not_after": "2026-10-12T13:36:30Z",
         "ceiling_seconds": 420, "requires": [["core", "admission_manifest"], ["core", "post"]], "effect": reader,
         "decoder": {"kind": "SESSION_START_V3", "verifier": "session_verifier"}, "pre_effect": supervisor,
         "hold_until": "2026-10-12T13:30:30Z", "slots": [{"slot": "S1", "at": "2026-10-12T13:29:02Z"}]},
        {"step": "capture_launch", "not_before": cap_nb, "not_after": cap_na, "ceiling_seconds": 750,
         "requires": [["core", "post"], ["step", "session_start"]], "effect": cap_row,
         "decoder": k9_decoder("capture_launch", cap_row, cap_nb, cap_na), "pre_effect": None, "hold_until": None,
         "slots": [{"slot": "C1", "at": cap_start}]}]
    files = k9_files(["capture_launch"])
    files.update({"ext/j4_hot_worker.py": "../vendor/j4_hot_worker.py", "ext/j4_codec.py": "@P_CODEX_J4_RECEIPT_CODEC_PY@",
                  "ext/session_verifier.py": "@P_CODEX_REVIEWED_SESSION_START_VERIFIER_PY@",
                  "ext/c6_bridge.py": "@P_CODEX_REVIEWED_C6_SNAPSHOT_READER_VERIFIER_PY@",
                  "ext/capacity_verifiers.py": "@P_CODEX_REVIEWED_CAPACITY_VERIFIERS_PY@",
                  "ext/ready_verifiers.py": "@P_CODEX_REVIEWED_READY_VERIFIERS_PY@",
                  "docs/bounded_readback_rule.json": "@P_APPROVED_BOUNDED_READBACK_RULE_JSON@"})
    external = dict(K9_EXTERNAL)
    external.update({"j4_codec": {"file": "ext/j4_codec.py", "identity": "verify"},
                     "session_verifier": {"file": "ext/session_verifier.py", "identity": "verify"},
                     "snapshot_reader": {"file": "ext/c6_bridge.py", "identity": "read_snapshot"},
                     "snapshot_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_snapshot"},
                     "readback_rule_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_rule"},
                     "readback_verifier": {"file": "ext/c6_bridge.py", "identity": "verify_readback"},
                     "cap_rule": {"file": "ext/capacity_verifiers.py", "identity": "verify_rule"},
                     "cap_original": {"file": "ext/capacity_verifiers.py", "identity": "verify_original"},
                     "cap_config": {"file": "ext/capacity_verifiers.py", "identity": "verify_config"},
                     "ready_rule": {"file": "ext/ready_verifiers.py", "identity": "verify_rule"},
                     "ready_ready": {"file": "ext/ready_verifiers.py", "identity": "verify_ready"}})
    spec = {"schema": bind.SPEC_SCHEMA, "lot": "DOWN", "lane": "DOWNSTREAM_AFTER_E6", "mode": "REAL",
            "owner_deadline": "2026-10-12T00:44:00Z", "decision_sha256": D1, "veto_max_age_seconds": 10,
            "initial_receipts": {"commit_result": "@P_UP_COMMIT_RESULT_ORIGINAL_SHA256@",
                                 "publish_launch": "@P_UP_PUBLISH_LAUNCH_ORIGINAL_SHA256@"},
            "imports": {r: {"source_lot": "UP", "request_sha256": "@P_UP_REQUEST_SHA256@",
                            "bound_sha256": "@P_UP_BOUND_SHA256@"} for r in ("commit_result", "publish_launch")},
            "files": files, "external": external, "k9": k9_section(["capture_launch"], secrets_root, networks),
            "tasks": tasks, "extended": {"steps": steps}, "bootstrap": None,
            "gate": {"scope": {"build_sha": REVISION, "image_id": IMAGE, "document_order_sha256": ORDER,
                               "release_sha256": RELEASE, "package_sha256": PACKAGE,
                               "calendar_pin_sha256": "@P_CALENDAR_PIN_SHA256@",
                               "runtime_authority_sha256": "@P_RUNTIME_AUTHORITY_SHA256@", "owner_uid": 0,
                               "manifest_directory": "@P_MANIFEST_DIRECTORY@", "session_open": "2026-10-12T13:30:00Z",
                               "not_before": "2026-10-12T10:37:30Z", "not_after": "2026-10-12T10:50:00Z",
                               "view_opens_at": "2026-10-12T10:38:00Z", "require_go_mode": "INDIVIDUAL"},
                     "journal_directory": rt.EPOCH04_JOURNAL_ROOT, "snapshot_reader": "snapshot_reader",
                     "snapshot_verifier": "snapshot_verifier",
                     "readback": {"rule": "docs/bounded_readback_rule.json", "rule_verifier": "readback_rule_verifier",
                                  "readback_verifier": "readback_verifier"}},
            "capacity": {"mode": "REAL", "lots": {"m3": "BOOT", "j": "DOWN", "activation": "CAP"},
                         "sources": {"m3": "@P_M3_ACTIVATE_PROGRAM_SHA256@", "j": J4_PROGRAMS["hot_worker"],
                                     "activation": "@P_CAPACITY_MONDAY04_PROGRAM_SHA256@"},
                         "verifiers": {"rule": "cap_rule", "original": "cap_original", "config": "cap_config"},
                         "config_path": rt.EPOCH04_CAPACITY_ROOT + "/config/capacity-final-2026-10-12.json"},
            "ready": {"mode": "REAL", "calendar_sha256": "@P_CALENDAR_PIN_SHA256@", "not_before": "2026-10-12T13:29:00Z",
                      "not_after": "2026-10-12T13:29:50Z", "max_wait_seconds": 48, "poll_seconds": 0.25,
                      "ready_path": rt.EPOCH04_READY_PATH, "verifiers": {"rule": "ready_rule", "ready": "ready_ready"}},
            "j4": {"protocol": "WARM_IMAGE10_ACTUAL_OBSERVATION", "hot_worker_source": "ext/j4_hot_worker.py",
                   "programs": dict(J4_PROGRAMS),
                   "originals": {n: "@P_J4_ORIGINAL_%s_SHA256@" % n.upper()
                                 for n in sorted(set(rt.J4_ORIGINALS) - set(rt.J4_LOT_ORIGINALS))},
                   "bridge": {"bootstrap": "bootstrap", "authorize": "authorize", "general_read": "general_read",
                              "general_verify": "general_verify"},
                   "general_authority_sha256": "@P_J4_GENERAL_AUTHORITY_SHA256@",
                   "general_source_identity": "@P_J4_GENERAL_SOURCE_IDENTITY@"}}
    return spec


# ------------------------------------------------------------------ write / validate
def write(path, spec, comment):
    raw = (json.dumps({"_comment": comment, "spec": spec}, sort_keys=True, indent=1) + "\n").encode("ascii")
    fd = os.open(str(path), os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW, 0o600)
    try:
        os.write(fd, raw)
    finally:
        os.close(fd)
    return rt.sha(raw)


def placeholders(value, out=None):
    out = set() if out is None else out
    if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
        out.add(value)
    elif isinstance(value, dict):
        for v in value.values():
            placeholders(v, out)
    elif isinstance(value, list):
        for v in value:
            placeholders(v, out)
    return out


SYNTHETIC_MODULE = b'''"""SYNTHETIC FILL-IN (validation of the spec shape only; never a verifier)."""
def _accept(*args):
    return None
verify = verify_approval = verify_original = verify_step = verify_rule = verify_readback = _accept
verify_config = verify_ready = verify_snapshot = read_snapshot = _accept
'''


def fill(spec, tmp):
    """Replace ONLY the declared @P_...@ placeholders with synthetic values (files -> synthetic bytes in tmp)."""
    spec = copy.deepcopy(spec)
    module = Path(tmp) / "synthetic_module.py"
    module.write_bytes(SYNTHETIC_MODULE)
    doc = Path(tmp) / "synthetic_doc.json"
    doc.write_bytes(b'{"synthetic":true}')
    for rel, local in list(spec["files"].items()):
        if local.startswith("@P_"):
            spec["files"][rel] = str(module if rel.endswith(".py") else doc)
    values = {"@P_MANIFEST_DIRECTORY@": "/var/lib/c3po-capacity-e04/payload",
              "@P_E6_DOCUMENT_PATH@": "/var/lib/c3po/r2d2-v2-k9-20261012/e6/E6_04.json",
              "@P_J4_GENERAL_SOURCE_IDENTITY@": "SYNTHETIC_FILL_IN"}

    def walk(value):
        if isinstance(value, str) and value.startswith("@P_") and value.endswith("@"):
            return values.get(value, hashlib.sha256(value.encode("ascii")).hexdigest())
        if isinstance(value, dict):
            return {k: walk(v) for k, v in value.items()}
        if isinstance(value, list):
            return [walk(v) for v in value]
        return value
    return walk(spec)


def runtime_stub(lay):
    return rt.canonical({"schema": rt.RUNTIME_SCHEMA, "layout_sha256": rt.sha(rt.canonical(lay))})


def validate_up(physical=True):
    spec = build_up()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-10T12:30:00Z", LOTS, physical=physical)
    plan = json.loads((LOTS / PLANS / "plans" / "prove_launch.json").read_bytes())
    return {"status": "UP_SPEC_VALID_WITH_FILL_INS", "physical_guards": physical, "image_id": IMAGE,
            "code_revision": plan["constants"]["code_revision"], "package_sha256": plan["constants"]["package_sha256"],
            "runner_sha256": authority["files"]["ext/k9_runner04.py"], "release_sha256": plan["constants"]["release_sha256"],
            "policy_sha256": plan["constants"]["policy_sha256"], "act_b_sha256_DRAFT": plan["constants"]["act_b_sha256"],
            "go_sha256_DRAFT": plan["go_sha256"], "slots": len(authority["slots"]), "slack": slack_table(spec),
            "placeholders": sorted(placeholders(spec)) + ["ACT_B_04 (plan constants)", "K9_GO_04 (plan go_sha256)"]}


def validate_down(physical=True):
    spec = build_down()
    with tempfile.TemporaryDirectory() as tmp:
        filled = fill(spec, tmp)
        lay = layout()
        authority_raw, request_raw, authority, q, extra = bind.build_lot(filled, lay, runtime_stub(lay),
                                                                         "2026-10-11T23:00:00Z", LOTS, physical=physical)
    return {"status": "DOWN_DRAFT_VALID_WITH_FILL_INS", "physical_guards": physical,
            "session_start_at": [s for s in authority["slots"] if s["target"] == "session_start"][0]["at"],
            "ready_check_at": [s for s in authority["slots"] if s["target"] == "ready_check"][0]["at"],
            "slots": len(authority["slots"]), "slack": slack_table(spec), "placeholders": sorted(placeholders(spec))}


UP_COMMENT = ["L12-HOST v3.1 UP lot SPEC, REAL values; build_specs.py builds it from the gen_k9_plans04 output.",
              "DRAFT until Saturday: act B 04 and the K9 04 GO (plan bytes and hashes change; regenerate the plans with",
              "the real files and rebuild), ext/k9_verifiers04.py (Codex-reviewed REAL verifiers), D-NET network names,",
              "secrets_root (REQUEST parameter, decision pending Codex). Not signed data until the owner's Assino.",
              "v3.1: every LAUNCH row's inner KILL is budget - 65 s (generator: budget - 35 s) so the effect may start up",
              "to 45 s after its instant (30 s beyond the 15 s gate allowance); Codex ruling on the runner's DEADLINE",
              "receipt window (55 s -> 25 s + lateness) requested (CONTRACT 9.3)."]
DOWN_COMMENT = ["L12-HOST v3.1 DOWN lot SPEC DRAFT (B3: no PRE_OPEN reader start; one late session start claim at",
                "10:29:02 BRT; K9 capture as an EXTENDED step; v3.1 early read-only ready_check R0 at 09:30 BRT).",
                "Every @P_...@ is unknown today. Supervisor state root /var/lib/c3po-bar/supervisor-e04 and config",
                "/etc/c3po-reader-e04/supervisor are PROPOSALS for INSTALL_TREE04. J budget 300 s and the J2/J3 instants",
                "are drafts. Not signed data."]


def main(argv):
    if argv == ["write"]:
        out = {"UP.SPEC.json": write(LOTS / "UP.SPEC.json", build_up(), UP_COMMENT),
               "DOWN.SPEC.DRAFT.json": write(LOTS / "DOWN.SPEC.DRAFT.json", build_down(), DOWN_COMMENT)}
    elif argv == ["validate"]:
        out = {"UP": validate_up(), "DOWN": validate_down()}
    else:
        raise SystemExit("usage: build_specs.py write|validate")
    print(json.dumps(out, sort_keys=True, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
