"""K10: the single-use and binding guards of the dispatcher and of the launcher generated for this operation, each
exercised directly. The family's conformance suite (the frozen core's tests/conformance.py) leaves these unpinned for
K10: a reviewer's mutants on the generated bytes survived it (review of 2026-10-02: D01, D02, D03, D04, D06, D07, D08,
D10, D12, D13, D16, L01). The worst case was single use itself: the core's test of it passes when the spawn marker is
not written, because its transport raises an AssertionError that the dispatcher's own "except Exception" swallows, and
the FileExistsError it expects then comes from the receipt file of the first resume, AFTER the transport was reached.
Here the transport counts its calls. Synthetic local files only: no SSH, no host, no key, no GO."""
import hashlib
import json
import os
from datetime import datetime,timedelta
from pathlib import Path
import subprocess
import sys

import pytest

import family as f
import k10

def sha(raw):return hashlib.sha256(raw).hexdigest()

def counting(dispatch,calls):
    inner=dispatch.fake()
    def run(payload,**kwargs):
        calls.append(sha(payload));return inner(payload,**kwargs)
    return run

def test_second_resume_never_reaches_the_transport(tmp_path):
    docs,_=k10.case();dispatch=f.Dispatch(docs,tmp_path);published=dispatch.proof(dispatch.prepare());calls=[]
    assert dispatch.resume(published,counting(dispatch,calls))['status']=='KNOWN_PARTIAL' and calls==[sha(dispatch.payload)]
    with pytest.raises(FileExistsError):dispatch.resume(published,counting(dispatch,calls))
    assert len(calls)==1,'the payload was offered to the transport twice'
    # even when the receipts of the first resume are gone (a wiped attempt directory keeps spawn.claim only)
    attempt=Path(dispatch.config['attempt_directory'])
    for name in ('stdout.private.json','stderr.private','exit.json'):(attempt/name).unlink()
    with pytest.raises(FileExistsError):dispatch.resume(published,counting(dispatch,calls))
    assert len(calls)==1

def test_what_is_sent_is_the_bundle_of_the_authenticated_documents(tmp_path):
    docs,_=k10.case();k=docs.k;dispatch=f.Dispatch(docs,tmp_path)
    other=dispatch.payload.replace(b"exit_code=3;result=module.run(",b"exit_code=3;result=module.run (")
    assert other!=dispatch.payload
    dispatch.config['payload']=dispatch.put('payload',other);dispatch.pin=dispatch.put('config',f.canonical(dispatch.config))
    assert f.refusal(dispatch.prepare)=='FINAL_BUNDLE_BYTES' and not dispatch.claims()
    # a bundle of ANOTHER request of the same operation (the spare) under the primary's config
    docs2,_=k10.case(now=docs.now+timedelta(minutes=1));d2=f.Dispatch(docs2,tmp_path/'x') if (tmp_path/'x').mkdir() is None else None
    dispatch.config['payload']=dispatch.put('payload',d2.payload);dispatch.pin=dispatch.put('config',f.canonical(dispatch.config))
    assert f.refusal(dispatch.prepare)=='FINAL_BUNDLE_BYTES' and not dispatch.claims()

def test_config_window_wider_than_a_signed_window_is_refused_before_the_claim(tmp_path):
    docs,_=k10.case();dispatch=f.Dispatch(docs,tmp_path);now=docs.now
    for field,value in (('not_before',(now-timedelta(seconds=1)).isoformat()),('not_after',(now+timedelta(minutes=5,seconds=1)).isoformat())):
        saved=dispatch.config[field];dispatch.config[field]=value
        dispatch.config['latest_start']=(datetime.fromisoformat(dispatch.config['not_after'])-timedelta(seconds=80)).isoformat()
        dispatch.save(rebind=False);assert f.refusal(lambda:dispatch.prepare(clock=lambda:now))=='INNER_WINDOW' and not dispatch.claims()
        dispatch.config[field]=saved
    # the GO narrower than the config
    dispatch.config['latest_start']=(now+timedelta(seconds=220)).isoformat()
    docs.go['not_after']=(now+timedelta(minutes=4)).isoformat();dispatch.save()
    assert f.refusal(dispatch.prepare)=='INNER_WINDOW' and not dispatch.claims()

def test_budget_pair_and_inner_hash_chain_and_command_pin_before_the_claim(tmp_path):
    docs,_=k10.case();k=docs.k
    d=tmp_path/'a';d.mkdir();dispatch=f.Dispatch(docs,d)
    dispatch.config['watchdog_seconds']=79;dispatch.config['latest_start']=(docs.now+timedelta(seconds=221)).isoformat();dispatch.save(rebind=False)
    assert f.refusal(dispatch.prepare)=='PREFLIGHT_BUDGET' and not dispatch.claims()
    d=tmp_path/'b';d.mkdir();dispatch=f.Dispatch(docs,d)
    dispatch.config['command_sha256']='a'*64;dispatch.save(rebind=False)
    assert f.refusal(dispatch.prepare) in ('GO_TRANSPORT_BINDING',) and not dispatch.claims()
    dispatch.save()                                        # the GO now names the wrong pin too: only COMMAND_PIN is left to refuse
    assert f.refusal(dispatch.prepare)=='COMMAND_PIN' and not dispatch.claims()
    # a broken chain between the documents: the dispatcher's own check, before the source's
    d=tmp_path/'c';d.mkdir();docs2,_=k10.case();dispatch=f.Dispatch(docs2,d)
    docs2.go['authority_sha256']='b'*64;raw=docs2.raw()
    for key,blob in (('go',raw[2]),):dispatch.config[key]=dispatch.put(key,blob)
    payload=k.l.build(k.source,*raw,expected_payload_sha256=sha(k.source),expected_request_sha256=sha(raw[0]),expected_authority_sha256=sha(raw[1]),expected_go_sha256=sha(raw[2]))
    dispatch.config['payload']=dispatch.put('payload',payload);dispatch.pin=dispatch.put('config',f.canonical(dispatch.config))
    assert f.refusal(dispatch.prepare)=='INNER_BINDINGS' and not dispatch.claims()

def test_key_and_known_hosts_are_pinned_before_the_claim(tmp_path):
    docs,_=k10.case();dispatch=f.Dispatch(docs,tmp_path)
    Path(dispatch.config['known_hosts']['path']).write_bytes(b'CHANGED')
    assert f.refusal(dispatch.prepare)=='LOCAL_PIN' and not dispatch.claims()

def test_resume_needs_the_claim_of_prepare_and_the_exact_intent(tmp_path):
    docs,_=k10.case();dispatch=f.Dispatch(docs,tmp_path);prepared=dispatch.prepare();published=dispatch.proof(prepared);calls=[]
    claim=dispatch.claims()[0];raw=claim.read_bytes();claim.unlink();claim.write_bytes(raw.replace(b'GO_CLAIM_V1',b'GO_CLAIM_V2'));os.chmod(claim,0o600)
    with pytest.raises(ValueError):dispatch.resume(published,counting(dispatch,calls))
    assert calls==[] and not (Path(dispatch.config['attempt_directory'])/'spawn.claim').exists()
    claim.unlink();claim.write_bytes(raw);os.chmod(claim,0o600)
    # an intent with another payload hash, published with its own hash
    intent_path=Path(dispatch.config['attempt_directory'])/'intent.json';intent=json.loads(intent_path.read_bytes())
    forged=f.canonical(dict(intent,payload_sha256='c'*64));intent_path.unlink();intent_path.write_bytes(forged);os.chmod(intent_path,0o600)
    proof=dispatch.proof({'intent_sha256':sha(forged)})
    with pytest.raises(ValueError):dispatch.resume(proof,counting(dispatch,calls))
    assert calls==[] and not (Path(dispatch.config['attempt_directory'])/'spawn.claim').exists()

def test_receipt_must_name_the_payload_it_ran_and_partial_receipts_are_bound_too(tmp_path):
    for index,status in enumerate(('KNOWN_COMPLETE','KNOWN_PARTIAL')):
        d=tmp_path/str(index);d.mkdir();docs,_=k10.case();dispatch=f.Dispatch(docs,d);m=docs.k.m
        out=f.canonical({'schema':m.RECEIPT_SCHEMA,'request_sha256':dispatch.config['request']['sha256'],'go_sha256':dispatch.config['go']['sha256'],'payload_sha256':'d'*64})
        result=dispatch.resume(dispatch.proof(dispatch.prepare()),dispatch.fake(out=out,status=status))
        assert result['status']=='UNCERTAIN' and result['code']=='TRANSPORT_OR_RECEIPT_REFUSED'

def test_launcher_refuses_a_source_that_is_not_the_pinned_one_on_stdin():
    docs,_=k10.case();k=docs.k;raws=docs.raw()
    payload=k.l.build(k.source,*raws,expected_payload_sha256=sha(k.source),expected_request_sha256=sha(raws[0]),expected_authority_sha256=sha(raws[1]),expected_go_sha256=sha(raws[2]))
    text=payload.decode();pin=sha(k.source);assert text.count("'payload': '%s'"%pin)==1
    forged=text.replace("'payload': '%s'"%pin,"'payload': '%s'"%('e'*64)).encode()
    done=subprocess.run([sys.executable,'-I','-B','-'],input=forged,stdout=subprocess.PIPE,stderr=subprocess.PIPE,env={'PATH':'/usr/bin:/bin'},timeout=60)
    out=json.loads(done.stdout);assert done.returncode==1 and done.stderr==b'' and out=={'schema':'HOSTOPS_STDIN_RESULT_V1','status':'REFUSED','code':'STDIN_SOURCE_PIN'}
    with pytest.raises(ValueError):k.l.build(k.source+b'\n',*raws,expected_payload_sha256=sha(k.source),expected_request_sha256=sha(raws[0]),expected_authority_sha256=sha(raws[1]),expected_go_sha256=sha(raws[2]))

def test_config_window_wider_than_the_request_alone_is_refused_before_the_claim(tmp_path):
    """Authority and GO signed for a longer window than the request: the config may not use the longer one."""
    docs,_=k10.case();now=docs.now;wide=(now+timedelta(minutes=10)).isoformat()
    docs.authority['not_after']=wide;docs.go['not_after']=wide;docs.chain();docs.authenticate()
    dispatch=f.Dispatch(docs,tmp_path)
    dispatch.config['not_after']=wide;dispatch.config['latest_start']=(now+timedelta(minutes=10)-timedelta(seconds=80)).isoformat();dispatch.save()
    assert f.refusal(dispatch.prepare)=='INNER_WINDOW' and not dispatch.claims()
