"""v3.3g probe (Fable, Mac, offline): compare D plans trees regenerated by the family generator's `plans` CLI from the
REAL issued inputs (app tree de96aee9, act B, certified release/policy, issued GO 757c3096...) with the issued
final-plans directory, file by file (sha256 only; never contents).

    python3 -I -B d_real_regen_compare.py <issued final-plans dir> <dir holding d-<engine>-py<NN>/ and .stdout> > OUT.json

For a tree made with the family engine, the manifest's differing keys are listed (expected: engine_rule.sha256 only).
"""
import hashlib
import json
from pathlib import Path
import sys


def listing(root):
    return {p.relative_to(root).as_posix(): hashlib.sha256(p.read_bytes()).hexdigest()
            for p in sorted(root.rglob("*")) if p.is_file()}


def main(issued_dir, runs_dir):
    issued_root, runs = Path(issued_dir), Path(runs_dir)
    issued = listing(issued_root)
    out = {"schema": "L12HOST_V33G_D_REAL_REGEN_COMPARE", "issued_final_plans": str(issued_root),
           "issued_files": len(issued), "issued_request_sha256": issued["K9_04_STEP_SET_REQUEST.json"],
           "issued_manifest_sha256": issued["K9_04_STEP_SET_MANIFEST.json"],
           "issued_plans": {k[6:-5]: v for k, v in issued.items() if k.startswith("plans/")}, "runs": {}}
    for d in sorted(runs.glob("d-*-py*")):
        if not d.is_dir():
            continue
        mine = listing(d)
        plans_equal = {k: mine.get(k) == v for k, v in issued.items() if k.startswith("plans/")}
        row = {"stdout": (runs / (d.name + ".stdout")).read_text().strip(), "files": len(mine),
               "same_file_set": set(mine) == set(issued),
               "differing": sorted(k for k in set(mine) | set(issued) if mine.get(k) != issued.get(k)),
               "request_sha256": mine["K9_04_STEP_SET_REQUEST.json"],
               "twelve_plans_identical": len(plans_equal) == 12 and all(plans_equal.values()),
               "runner_identical": all(mine.get(k) == v for k, v in issued.items() if k.startswith("tools/")),
               "manifest_sha256": mine["K9_04_STEP_SET_MANIFEST.json"]}
        a = json.loads((d / "K9_04_STEP_SET_MANIFEST.json").read_bytes())
        b = json.loads((issued_root / "K9_04_STEP_SET_MANIFEST.json").read_bytes())
        top = [k for k in sorted(set(a) | set(b)) if a.get(k) != b.get(k)]
        row["manifest_differing_keys"] = {
            "top": top, "inner": {k: [x for x in sorted(set(a[k]) | set(b[k])) if a[k].get(x) != b[k].get(x)]
                                  for k in top if isinstance(a.get(k), dict) and isinstance(b.get(k), dict)},
            "engine_rule_sha256": [a["engine_rule"]["sha256"], b["engine_rule"]["sha256"]]}
        out["runs"][d.name] = row
    out["all_requests_and_plans_identical"] = bool(out["runs"]) and all(
        r["request_sha256"] == out["issued_request_sha256"] and r["twelve_plans_identical"] and r["runner_identical"]
        for r in out["runs"].values())
    print(json.dumps(out, sort_keys=True, indent=1))
    return 0 if out["all_requests_and_plans_identical"] else 1


if __name__ == "__main__":
    raise SystemExit(main(*sys.argv[1:3]))
